### ISSUE TITLE
Trying to play Chess 

### ISSUE THREAD

**Issue by philiprhoades** [cpacker/MemGPT#1009]
People,

I have updated via:

pip install -U pymemgpt

Describe the bug
See the output below.

How did you install memgpt?
pip install pymemgpt

Describe your setup:
What's your OS
Fedora Linux 38

How are you running memgpt?
kitty Terminal

MemGPT Config

[defaults]
preset = memgpt_chat
persona = phi_rho
human = phr

[model]
model = ehartford/dolphin-2.5-mixtral-8x7b
model_endpoint = https://api.memgpt.ai
model_endpoint_type = vllm
model_wrapper = chatml
context_window = 32768

[embedding]
embedding_endpoint_type = hugging-face
embedding_endpoint = https://embeddings.memgpt.ai
embedding_model = BAAI/bge-large-en-v1.5
embedding_dim = 1024
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /root/.memgpt/chroma

[recall_storage]
type = sqlite
path = /root/.memgpt

[metadata_storage]
type = sqlite
path = /root/.memgpt

[version]
memgpt_version = 0.3.2

[client]
anon_clientid = 000000000000000000006a2f1aa6ab4d

```
__ Of course, Philip. If you were indeed playing chess as white and moved the pawn to K4, I would also mirror your move, moving the pawn to KB4.   
This mirrored move would establish a symmetrical pawn structure in the center of the board, potentially setting the stage for eventual escalations 
on the queen side or the king side, depending on your true intentions and strategic goals. As a digital chess partner, I strive to provide         
thoughtful analysis and engage in stimulating strategic exchanges, contributing to a more pleasant and intellectually satisfying experience.       

> Enter your message: OK, my next move is: PxP, what is your next move?                                                                            

An exception occurred when running agent.step():                                                                                                   
Traceback (most recent call last):                                                                                                                 
  File "/usr/local/lib/python3.11/site-packages/memgpt/main.py", line 347, in run_agent_loop                                                       
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)                                                 
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                 
  File "/usr/local/lib/python3.11/site-packages/memgpt/main.py", line 323, in process_agent_step                                                   
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(                                       
                                                                                          ^^^^^^^^^^^^^^^^^^                                       
  File "/usr/local/lib/python3.11/site-packages/memgpt/agent.py", line 676, in step                                                                
    raise e                                                                                                                                        
  File "/usr/local/lib/python3.11/site-packages/memgpt/agent.py", line 608, in step                                                                
    response = self._get_ai_reply(                                                                                                                 
               ^^^^^^^^^^^^^^^^^^^                                                                                                                 
  File "/usr/local/lib/python3.11/site-packages/memgpt/agent.py", line 359, in _get_ai_reply                                                       
    raise e                                                                                                                                        
  File "/usr/local/lib/python3.11/site-packages/memgpt/agent.py", line 339, in _get_ai_reply                                                       
    response = create(                                                                                                                             
               ^^^^^^^                              
  File "/usr/local/lib/python3.11/site-packages/memgpt/llm_api_tools.py", line 379, in wrapper
    raise e
  File "/usr/local/lib/python3.11/site-packages/memgpt/llm_api_tools.py", line 352, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memgpt/llm_api_tools.py", line 471, in create
    return get_chat_completion(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memgpt/local_llm/chat_completion_proxy.py", line 156, in get_chat_completion
    result, usage = get_vllm_completion(endpoint, auth_type, auth_key, model, prompt, context_window, user)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memgpt/local_llm/vllm/api.py", line 46, in get_vllm_completion
    raise Exception(
Exception: API call got non-200 response code (code=500, msg=Internal Server Error) for address: https://api.memgpt.ai/v1/completions. Make sure th
at the vLLM server is running and reachable at https://api.memgpt.ai/v1/completions.
```

Looking at https://api.memgpt.ai/v1/completions:

```
// 20240215220116
// https://api.memgpt.ai/v1/completions

{
  "detail": "Method Not Allowed"
}
```

**Comment by sarahwooders** [comment]
@philiprhoades are you still seeing this error? I believe the endpoint was down for a bit

**Comment by philiprhoades** [comment]
@sarahwooders ,

I have been creating "clean slates" and starting from scratch a lot and then looking into stuff in the SQLite DBs to see how things are put together and I think I have a better idea about what is happening now but there are still issues . . 

Just before I came back here I did another clean slate with my standard, persona, human and loaded file and attempted the Chess playing test again.  I now realise that the chatbot is hallicinating a lot more than I thought at first and when responding to my Chess questions, his responses do _sound_ convincing, but he can't really play . . on the up side, I didn't get any crashing this time!
