### ISSUE TITLE
API call got non-200 response code for address: http://127.0.0.1:5001/v1/api/v1/generate

### ISSUE THREAD

**Issue by ManuXD32** [cpacker/MemGPT#101]
When trying to run memgpt on top of a local LLM I get this error.
I follow the steps:
export OPENAI_API_BASE=http://127.0.0.1:5001/v1
export BACKEND_TYPE=webui

Then run:
python3 main.py --no_verify

And finally I get this warning followed by the mentioned error:

Warning: could not find an LLM wrapper for gpt-3.5-turbo, using the airoboros wrapper
Traceback (most recent call last):
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/main.py", line 498, in <module>
    app.run(run)
  File "/home/manu/miniconda3/envs/memgpt/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/manu/miniconda3/envs/memgpt/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/main.py", line 496, in run
    loop.run_until_complete(main())
  File "/home/manu/miniconda3/envs/memgpt/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/main.py", line 470, in main
    ) = await memgpt_agent.step(
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/memgpt/agent.py", line 545, in step
    raise e
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/memgpt/agent.py", line 492, in step
    response = await get_ai_reply_async(model=self.model, message_sequence=input_message_sequence, functions=self.functions)
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/memgpt/agent.py", line 115, in get_ai_reply_async
    raise e
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/memgpt/agent.py", line 96, in get_ai_reply_async
    response = await acreate(
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/memgpt/openai_tools.py", line 106, in wrapper
    raise e
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/memgpt/openai_tools.py", line 84, in wrapper
    return await func(*args, **kwargs)
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/memgpt/openai_tools.py", line 115, in acompletions_with_backoff
    return await get_chat_completion(**kwargs)
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/memgpt/local_llm/chat_completion_proxy.py", line 41, in get_chat_completion
    result = get_webui_completion(prompt)
  File "/home/manu/Escritorio/1. IAMIO/MemGPT/memgpt/local_llm/webui/api.py", line 28, in get_webui_completion
    raise Exception(f"API call got non-200 response code for address: {URI}")
Exception: API call got non-200 response code for address: http://127.0.0.1:5001/v1/api/v1/generate

**Comment by ManuXD32** [comment]
Okay, just found out that it was because I was using openai extension instead of just api.
