### ISSUE TITLE
memgpt benchmark  - client is not defined

### ISSUE THREAD

**Issue by dlaliberte** [cpacker/MemGPT#1030]
**Describe the bug**
Running memgpt benchmark (after configuring a working agent) fails with 'client' is not defined

**Please describe your setup**
```bash
(memgpt) PS C:\Users\danie\memgpt> memgpt benchmark 

Depending on your hardware, this may take up to 30 minutes. This will also create 15 new agents.

version = 0.3.3
An unexpected error occurred: name 'client' is not defined
Traceback (most recent call last):
  File "C:\Users\danie\memgpt\memgpt\benchmark\benchmark.py", line 23, in send_message
    response, tokens_accumulated = client.user_message(agent_id=agent_id, message=message, return_token_count=True)
                                   ^^^^^^
NameError: name 'client' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
...
  File "C:\Users\danie\memgpt\memgpt\benchmark\benchmark.py", line 62, in bench
    result, msg, tokens_accumulated = send_message(
                                      ^^^^^^^^^^^^^
  File "C:\Users\danie\memgpt\memgpt\benchmark\benchmark.py", line 38, in send_message
    return False, "An unexpected error occurred.", tokens_accumulated
                                                   ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'tokens_accumulated' where it is not associated with a value
```

**Additional context**
Fresh install of Ollama, and MemGPT.  

**MemGPT Config**
Please attach your `~/.memgpt/config` file or **copy-paste** (not copy _past_) it below.

```
[defaults]
preset = memgpt_chat
persona = sam_pov
human = cs_phd

[model]
model = openhermes
model_endpoint = http://127.0.0.1:11434
model_endpoint_type = ollama
model_wrapper = chatml
context_window = 16384

[embedding]
embedding_endpoint_type = local
embedding_dim = 384
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = C:\Users\danie\.memgpt\chroma
uri = 

[recall_storage]
type = sqlite
path = C:\Users\danie\.memgpt
uri = 

[metadata_storage]
type = sqlite
path = C:\Users\danie\.memgpt
uri = 

[version]
memgpt_version = 0.3.3

[client]
anon_clientid = 00000000000000000000c8cb9ef10d41

```

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use: openhermes from Ollama
- [ ] The local LLM backend you are using: Ollama on windows (yeah)
- [ ] Your hardware for the local LLM backend: Window 11

**Comment by sarahwooders** [comment]
This should be fixed by #1041
