### ISSUE TITLE
mac python3.9 run 'memgpt configure' got an error: `TypeError: 'staticmethod' object is not callable`

### ISSUE THREAD

**Issue by laoyin** [cpacker/MemGPT#1053]
**Describe the bug**
        mac python3.9 run 'memgpt configure' got an error: `TypeError: 'staticmethod' object is not callable`

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt  
- [ ] Describe your setup
  - mac os

run ```memgpt configure ```

**Screenshots**
```venv/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/Users/yinxingpan/freeswitch-data/third_server/random_call/venv/bin/memgpt", line 5, in <module>
    from memgpt.main import app
  File "/Users/yinxingpan/freeswitch-data/third_server/random_call/venv/lib/python3.9/site-packages/memgpt/__init__.py", line 3, in <module>
    from memgpt.client.client import Client as MemGPT
  File "/Users/yinxingpan/freeswitch-data/third_server/random_call/venv/lib/python3.9/site-packages/memgpt/client/client.py", line 9, in <module>
    from memgpt.server.server import SyncServer
  File "/Users/yinxingpan/freeswitch-data/third_server/random_call/venv/lib/python3.9/site-packages/memgpt/server/server.py", line 81, in <module>
    class LockingServer(Server):
  File "/Users/yinxingpan/freeswitch-data/third_server/random_call/venv/lib/python3.9/site-packages/memgpt/server/server.py", line 115, in LockingServer
    def user_message(self, user_id: str, agent_id: str, message: str) -> None:
TypeError: 'staticmethod' object is not callable
```

**Additional context**

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.

**Comment by Noel-Hol** [comment]
same here

**Comment by sarahwooders** [comment]
Unfortunately we only support Python version 3.10 or 3.11 - please upgrade to either of those versions!
