### ISSUE TITLE
TypeError: 'staticmethod' object is not callable when running MemGPT

### ISSUE THREAD

**Issue by betamod** [cpacker/MemGPT#1057]
**Describe the bug**
When attempting to run MemGPT using either the ‘memgpt’ run or ‘memgpt quickstart’ commands, I receive a TypeError: 'staticmethod' object is not callable error.

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt`
- [ ] Describe your setup
  - MacOS 14.2.1
  - In a conda environment, set up with Python Version: 3.9.18
  - How are you running: SSH Terminal

**Additional context**

**Example 1:** 
```
(memgpt) ➜  ~ memgpt run
Traceback (most recent call last):
  File "/Users/Matthew/anaconda3/envs/memgpt/bin/memgpt", line 5, in <module>
    from memgpt.main import app
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/__init__.py", line 3, in <module>
    from memgpt.client.client import Client as MemGPT
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/client/client.py", line 9, in <module>
    from memgpt.server.server import SyncServer
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/server/server.py", line 81, in <module>
    class LockingServer(Server):
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/server/server.py", line 115, in LockingServer
    def user_message(self, user_id: str, agent_id: str, message: str) -> None:
TypeError: 'staticmethod' object is not callable
```

  **Example 2:** 
```
  (memgpt) ➜  ~ memgpt quickstart
Traceback (most recent call last):
  File "/Users/Matthew/anaconda3/envs/memgpt/bin/memgpt", line 5, in <module>
    from memgpt.main import app
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/__init__.py", line 3, in <module>
    from memgpt.client.client import Client as MemGPT
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/client/client.py", line 9, in <module>
    from memgpt.server.server import SyncServer
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/server/server.py", line 81, in <module>
    class LockingServer(Server):
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/server/server.py", line 115, in LockingServer
    def user_message(self, user_id: str, agent_id: str, message: str) -> None:
TypeError: 'staticmethod' object is not callable
```

**Steps to reproduce:** 

 Installation process:
    * Created Conda environment: conda create --name memgpt python=3.9.18
    * Activated environment: conda activate memgpt
    * Installed MemGPT: pip install pymemgpt

I expected the MemGPT quickstart options to be displayed, allowing me to start interacting with a MemGPT agent but no joy

I tried updating MemGPT with pip install pymemgpt -U  I tried reseting to reconfigure MemGPT's default settings by running, ‘memgpt configure’ however the error persists:  

```
(memgpt) ➜  ~ memgpt configure
Traceback (most recent call last):
  File "/Users/Matthew/anaconda3/envs/memgpt/bin/memgpt", line 5, in <module>
    from memgpt.main import app
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/__init__.py", line 3, in <module>
    from memgpt.client.client import Client as MemGPT
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/client/client.py", line 9, in <module>
    from memgpt.server.server import SyncServer
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/server/server.py", line 81, in <module>
    class LockingServer(Server):
  File "/Users/Matthew/anaconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/server/server.py", line 115, in LockingServer
    def user_message(self, user_id: str, agent_id: str, message: str) -> None:
TypeError: 'staticmethod' object is not callable
```

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.

```
(memgpt) ➜  ~ cat .memgpt/config

cat: .memgpt/config: No such file or directory
```
It seems the ~/.memgpt/config file hasn't been created yet. Might this be because I haven't successfully run the memgpt configure command without encountering the staticmethod error?

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:
- [ ] The exact model you're trying to use: mistral instruct vo 2 7B Q4_K_S gguf
- [ ] The local LLM backend you are using: LM Studio
- [ ] Your hardware for the local LLM backend: locally on my M1 MacBook Pro

Please note that while I am a technically advanced user, I am not a programmer. I got this far by trying to follow your documentation and the help of Google Gemini. So hopefully the above makes sense.

**Comment by tombedor** [comment]
update python to > 3.10

**Comment by tyler-suard-parker** [comment]
I am getting this same error, even when using Python 3.11.9:

.venv\lib\site-packages\memgpt\server\server.py", line 115, in LockingServer
    def user_message(self, user_id: str, agent_id: str, message: str) -> None:
TypeError: 'staticmethod' object is not callable
