### ISSUE TITLE
cannot import name 'HuggingFaceEmbedding' from 'llama_index.embeddings' (unknown location)

### ISSUE THREAD

**Issue by barmajahssr** [cpacker/MemGPT#1079]
really spent hours struggling with this issue. installing reinstalling, upgrading  lamaindex,hugginface. it still throws this error when running memgpt:    🧬 Creating new agent...
->  🤖 Using persona profile 'sam_pov'
->  🧑 Using human profile 'basic'
Traceback (most recent call last):
  File "/home/iiiymem/memgpt/memgptvenv/bin/memgpt", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/memgpt/cli/cli.py", line 668, in run
    memgpt_agent = Agent(
                   ^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/memgpt/agent.py", line 258, in __init__
    self.persistence_manager = LocalStateManager(agent_state=self.agent_state)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/memgpt/persistence_manager.py", line 56, in __init__
    self.archival_memory = EmbeddingArchivalMemory(agent_state)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/memgpt/memory.py", line 373, in __init__
    self.embed_model = embedding_model(agent_state.embedding_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/memgpt/embeddings.py", line 182, in embedding_model
    return default_embedding_model()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iiiymem/memgpt/memgptvenv/lib/python3.11/site-packages/memgpt/embeddings.py", line 137, in default_embedding_model
    from llama_index.embeddings import HuggingFaceEmbedding
ImportError: cannot import name 'HuggingFaceEmbedding' from 'llama_index.embeddings' (unknown location)

**Comment by quantumalchemy** [comment]
getting same on the 0.3.4 upgrade -- trying the pymemgpt[local]l embedding now that the : embeddings.memgpt.ai
is showing: ' error: inputs must have less than 512 tokens. '    So we are boxed out on any use of documents

**Comment by thefux** [comment]
to work around, for those who use the github repo:

`pip install llama-index-embeddings-huggingface`

and then replace the import as below:
`from llama_index.embeddings import HuggingFaceEmbedding` -> `from llama_index.embeddings.huggingface import HuggingFaceEmbedding
`
this fixed the issue for me at least

**Comment by Damian666** [comment]
same error for me, but happens when i try to run with persona and human

**Comment by quantumalchemy** [comment]
> to work around, for those who use the github repo:
> 
> `pip install llama-index-embeddings-huggingface`
> 
> and then replace the import as below: `from llama_index.embeddings import HuggingFaceEmbedding` -> `from llama_index.embeddings.huggingface import HuggingFaceEmbedding ` this fixed the issue, for me at least

did you want to push that fix ?

**Comment by thefux** [comment]
> > to work around, for those who use the github repo:
> > `pip install llama-index-embeddings-huggingface`
> > and then replace the import as below: `from llama_index.embeddings import HuggingFaceEmbedding` -> `from llama_index.embeddings.huggingface import HuggingFaceEmbedding ` this fixed the issue, for me at least
> 
> did you want to initiate a pull with that fix ?

yeah sure, will push later

**Comment by sarahwooders** [comment]
Closing since #1087 is merged, but please re-open if you keep having this issue!
