### ISSUE TITLE
Getting python stacktrace when asking normal queries to the agent (I use the less expensive ChatGPT4 model)

### ISSUE THREAD

**Issue by distributev** [cpacker/MemGPT#1154]
What I suspect (but I am not sure)

This agent is using the 3x less expensive GPT-4-1106-preview model (vs GPT-4-0613 which costs more) - I did not get this exception immediately but after a short conversation with the agent in which it become clear to  me that he is not aware of his own persona from which it was created. This never happened with the agents created using the more expensive  GPT-4-0613 - I insisted to "reteach" the new agent his own persona and when I pasted him again the text and tried to send it I started to receive this python stacktrace and could not recover. Even if I do /exit and I come again to the same agent I get the same stacktrace and basically this agent is not un-usable and I need to delete and create him again.

I did delete and (re)created the agent twice and it happened the same. 

I never saw this in the previous days when my agents were created using the more expensive GPT-4-0613.

These are only suppositions and I am not sure that this is what is happening.

```An exception occurred when running agent.step(): 
Traceback (most recent call last):
  File "/home/infraworker/apps/program-files/custom-ai-tool-memgpt/memgpt/main.py", line 370, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infraworker/apps/program-files/custom-ai-tool-memgpt/memgpt/main.py", line 346, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
                                                                                          ^^^^^^^^^^^^^^^^^^
  File "/home/infraworker/apps/program-files/custom-ai-tool-memgpt/memgpt/agent.py", line 747, in step
    raise e
  File "/home/infraworker/apps/program-files/custom-ai-tool-memgpt/memgpt/agent.py", line 669, in step
    response = self._get_ai_reply(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/infraworker/apps/program-files/custom-ai-tool-memgpt/memgpt/agent.py", line 413, in _get_ai_reply
    raise e
  File "/home/infraworker/apps/program-files/custom-ai-tool-memgpt/memgpt/agent.py", line 393, in _get_ai_reply
    response = create(
               ^^^^^^^
  File "/home/infraworker/apps/program-files/custom-ai-tool-memgpt/memgpt/llm_api_tools.py", line 352, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/infraworker/apps/program-files/custom-ai-tool-memgpt/memgpt/llm_api_tools.py", line 430, in create
    return openai_chat_completions_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infraworker/apps/program-files/custom-ai-tool-memgpt/memgpt/llm_api_tools.py", line 210, in openai_chat_completions_request
    raise http_err
  File "/home/infraworker/apps/program-files/custom-ai-tool-memgpt/memgpt/llm_api_tools.py", line 202, in openai_chat_completions_request
    response.raise_for_status()  # Raises HTTPError for 4XX/5XX status
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/pymemgpt-b04PkZWQ-py3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.openai.com/v1/chat/completions```

**Comment by sarahwooders** [comment]
I'm not sure what's going on here - maybe OpenAI was down? Did this continue to be an issue? I'm going to close this for now but please feel free to re-open.
