### ISSUE TITLE
Unable to run/start. No module named 'llama_index.embeddings.huggingface'

### ISSUE THREAD

**Issue by ProtoBelisarius** [cpacker/MemGPT#1162]
**Describe the bug**
I configured memgpt for local use but when I try to run it, the following error occurs:

```
memgpt run

 Creating new agent...
->  🤖 Using persona profile: 'sam_pov'
->  🧑 Using human profile: 'basic'
Traceback (most recent call last):
  File "/home/username/Git/memgpt/venv/bin/memgpt", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/memgpt/cli/cli.py", line 674, in run
    memgpt_agent = Agent(
                   ^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/memgpt/agent.py", line 264, in __init__
    self.persistence_manager = LocalStateManager(agent_state=self.agent_state)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/memgpt/persistence_manager.py", line 55, in __init__
    self.archival_memory = EmbeddingArchivalMemory(agent_state)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/memgpt/memory.py", line 369, in __init__
    self.embed_model = embedding_model(agent_state.embedding_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/memgpt/embeddings.py", line 201, in embedding_model
    return default_embedding_model()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/Git/memgpt/venv/lib/python3.11/site-packages/memgpt/embeddings.py", line 137, in default_embedding_model
    from llama_index.embeddings.huggingface import HuggingFaceEmbedding
ModuleNotFoundError: No module named 'llama_index.embeddings.huggingface'
```

**Please describe your setup**
- [x] How did you install memgpt?
  - `pip install pymemgpt`
- [x] Describe your setup
  - Linux(Arch)
  - Terminal(bash)
  - running in a python3.11 venv

**Screenshots**

**Additional context**

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.

---
```
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model_endpoint = http://localhost:5001
model_endpoint_type = koboldcpp
model_wrapper = chatml
context_window = 8192

[embedding]
embedding_endpoint_type = local
embedding_dim = 384
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /home/belisarius/.memgpt/chroma

[recall_storage]
type = sqlite
path = /home/belisarius/.memgpt

[metadata_storage]
type = sqlite
path = /home/belisarius/.memgpt

[version]
memgpt_version = 0.3.6

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000
```

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- Hermes-2-Pro-Mistral-7B.Q8_0.gguf
- latest koboldcpp-rocm git (from yellowrose) compiled for OpenBLAS and HIPBLAS
- local (R9 5900X, RX 6800XT, 64GB RAM)

**Comment by ProtoBelisarius** [comment]
Installing
`pip install llama-index-embeddings-huggingface llama-index-llms-huggingface llama-index-core`
as well fixed the issue, although I have no idea if all of the packages are necessary.

**Comment by znfgnu** [comment]
It's been mentioned in docs: https://memgpt.readme.io/docs/local_llm

```
pip install pymemgpt[local]
```

**Comment by sarahwooders** [comment]
As @znfgnu mentioned to run with `embedding_endpoint_type = local` you need to install `pip install pymemgpt[local]`. There have also been a lot of other llama-index related install issues -- for those, I recommend deleting and re-creating your python env.
