### ISSUE TITLE
Issue with latest memgpt-server:0.3.7 image

### ISSUE THREAD

**Issue by davidkundrats** [cpacker/MemGPT#1202]
**Describe the bug**

I am trying to use docker compose to orchestrate the memgpt and vectordb containers. After yesterdays new image push (digest: sha256:462aafe2b7459fb0679e4dfda116d79586c0d72894d972e841299f6c7fd4c126), I am receiving the (pictured below) error: "Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "memgpt": executable file not found in $PATH: unknown". 

steps: 
add .env file with all necessary variables
compose.yaml is unmodified
docker compose up
*error* 

**Please describe your setup**
- [ ] How did you install memgpt?
  - git clone 
  - poetry shell
  - poetry install
- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  - Windows 10 running WSL2
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)
  - docker container

**Screenshots**
![error](https://github.com/cpacker/MemGPT/assets/98171693/dac1fd07-4ee7-430d-86de-fb225406f6b0)

**Additional context**

I tried running the uvicorn server manually from a container with the new image, and it returned this error: 

uvicorn memgpt.server.rest_api.server:app --host 0.0.0.0 --port 8083
Loading config from /root/.memgpt/config
Traceback (most recent call last):
  File "/app/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/memgpt/server/rest_api/server.py", line 53, in <module>
    server: SyncServer = SyncServer(default_interface=interface)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/server/server.py", line 228, in __init__
    model=self.config.default_llm_config.model,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'

Luckily I had an image that was pushed 5 days ago on a different device that I tested on the same machine experiencing the error (digest: sha256:159f72bbbf4e7b1708d0c8175a8709a6972af90e14fece1e4e2b7a5acb2b4f68) and it worked perfectly fine.  
I also could run the uvicorn server manually on the previous image. 

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = gpt-3.5-turbo-16k
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 16385

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-ada-002
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /home/david/.memgpt/chroma

[recall_storage]
type = sqlite
path = /home/david/.memgpt

[metadata_storage]
type = sqlite
path = /home/david/.memgpt

[version]
memgpt_version = 0.3.7

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000
---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by sarahwooders** [comment]
@davidkundrats thanks for reporting this! I think I accidentally pushed a broken version of the container to the repo - could you please try re-pulling the image and try again?

**Comment by davidkundrats** [comment]
@sarahwooders thanks for the quick reply - i pulled down the image you just pushed and I think it may be broken elsewhere; now throwing this error: 

memgpt_server-1  | ValueError: Postgres URI not provided

even though it is provided and acknowledges that it is when spinning up the container: 

Overriding DB config URI with environment variable: postgresql://sensitive-info-ex 

no changes to the compose.yaml file besides the image. Still works with the image from a few days ago to, after changing back.

**Comment by sarahwooders** [comment]
This should hopefully fix that issue https://github.com/cpacker/MemGPT/pull/1204 

Sorry about the various bugs, we're still iterating on how the compose file should pass config info into the server!

**Comment by davidkundrats** [comment]
no worries! thanks for the update
