### ISSUE TITLE
Your system has an unsupported version of sqlite3

### ISSUE THREAD

**Issue by deadbeef-development** [cpacker/MemGPT#1206]
**Describe the bug**
When I use `memgpt run`, I receive this error:
```
RuntimeError: Your system has an unsupported version of sqlite3. Chroma                     requires sqlite3 >= 3.35.0.
Please visit                     https://docs.trychroma.com/troubleshooting#sqlite to learn how                     to upgrade.
```

**Please describe your setup**
I am attempting to run MemGPT in a codespace (focal).
1. I created a virtual environment, `python3 -m venv .venv`.
2. I installed pymemgpt, `.venv/bin/pip install 'pymemgpt~=0.3'` (It installed version 0.3.7).
3. I ran memgpt, `.venv/bin/memgpt run`.
4. It asked me how I would like to set up MemGPT, so I answered `Use OpenAI (requires an OpenAI API key)`.
5. I provided my API key.
6. After providing the API key, it started off good with some colorful emojis. However, an exception occured and it exited with code `1`:
```
? How would you like to set up MemGPT? Use OpenAI (requires an OpenAI API key)

? Enter your OpenAI API key (starts with 'sk-', see https://platform.openai.com/api-keys): <REDACTED FOR GITHUB ISSUE>
📖 MemGPT configuration file updated!
🧠 model        -> gpt-4
🖥️  endpoint     -> https://api.openai.com/v1

🧬 Creating new agent...
->  🤖 Using persona profile: 'sam_pov'
->  🧑 Using human profile: 'basic'
Traceback (most recent call last):
  File "/workspaces/Python-Playground/.venv/bin/memgpt", line 8, in <module>
    sys.exit(app())
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/typer/core.py", line 783, in main
    return _main(
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/memgpt/cli/cli.py", line 683, in run
    memgpt_agent = Agent(
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/memgpt/agent.py", line 264, in __init__
    self.persistence_manager = LocalStateManager(agent_state=self.agent_state)
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/memgpt/persistence_manager.py", line 55, in __init__
    self.archival_memory = EmbeddingArchivalMemory(agent_state)
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/memgpt/memory.py", line 374, in __init__
    self.storage = StorageConnector.get_archival_storage_connector(user_id=agent_state.user_id, agent_id=agent_state.id)
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/memgpt/agent_store/storage.py", line 124, in get_archival_storage_connector
    return StorageConnector.get_storage_connector(TableType.ARCHIVAL_MEMORY, config, user_id, agent_id)
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/memgpt/agent_store/storage.py", line 103, in get_storage_connector
    from memgpt.agent_store.chroma import ChromaStorageConnector
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/memgpt/agent_store/chroma.py", line 4, in <module>
    import chromadb
  File "/workspaces/Python-Playground/.venv/lib/python3.10/site-packages/chromadb/__init__.py", line 79, in <module>
    raise RuntimeError(
RuntimeError: Your system has an unsupported version of sqlite3. Chroma                     requires sqlite3 >= 3.35.0.
Please visit                     https://docs.trychroma.com/troubleshooting#sqlite to learn how                     to upgrade.
```

Interestingly, when I run `sqlite3 --version`, it prints `3.41.2`. This indicates that I have a greater version than the minimal requirement of `3.35.0`.

I decided to visit https://docs.trychroma.com/troubleshooting#sqlite and try some of the suggestions.

**Suggestion 1: Install the latest version of Python 3.10**:
I was already at version `3.10.13`, however I noticed that `3.10.14` was available (https://www.python.org/downloads/release/python-31014/).

1. I went ahead and installed from source, specifying altinstall.
2. I created another virtual environment using Python `3.10.14`.
3. Installed `pymemgpt~=0.3` into the `3.10.14` virtual environment (It installed `pymemgpt==0.3.7`)
4. Sadly I receive the same error, `Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.`

I decided to also give Python `3.11.8` a try, using similar steps as above. However, the result was the same.

**Suggestion 2: Install pysqlite3-binary**:
The same issue persists after installing `pysqlite3-binary` in all three virtual environments (Python 3.10.13, 3.10.14, and 3.11.8).

**MemGPT Config**
---
```
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = gpt-4
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 8192

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /home/codespace/.memgpt/chroma

[recall_storage]
type = sqlite
path = /home/codespace/.memgpt

[metadata_storage]
type = sqlite
path = /home/codespace/.memgpt

[version]
memgpt_version = 0.3.7

[client]
anon_clientid = 000000000000000000000022482620a5
```

Any help on this would be greatly appreciated. Also, I am prepared to accept that Codespaces might not be supported currently.

**Comment by deadbeef-development** [comment]
Update: This seems to be a broader issue that doesn't necessarily pertain to just MemGPT.

The easiest solution I found is to use an updated version of Ubuntu, `jammy` (22.04), instead of `focal` (20.04, which Codespaces currently uses by default).

If you really want to use Codespaces for this, you can set up a custom Dev Container.

https://github.com/orgs/community/discussions/40871

https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers
