### ISSUE TITLE
'Message' object is not subscriptable when using ollama

### ISSUE THREAD

**Issue by tomsib2001** [cpacker/MemGPT#1244]
**Describe the bug**
Hi there, I'm trying to use MemGPT with Ollama and model `hexbenjamin/memgpt-dpo-uncensored:q8_0`, but I'm running into this error:

**Please describe your setup**
- [x] How did you install memgpt?
  -  clone repo, checkout tag `0.3.9` (also tried with main branch with the same result)
  - `pipx install poetry`
  - `poetry install`
  - `pip install pgvector pg8000 llama-index-embeddings-huggingface`
- [x] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  WSL2 Ubntu on Windows
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)
```
poetry shell
(pymemgpt-c3VCR-PY-py3.10) [USERNAME]@[HOSTNAME]:~/projets/MemGPT$ memgpt configure
Loading config from /[USER_DIRECTORY]/.memgpt/config
? Select LLM inference provider: local
? Select LLM backend (select 'openai' if you have an OpenAI compatible proxy): ollama
? Enter default endpoint: http://[LOCALHOST]:11434
? Is your LLM endpoint authenticated? (default no) No
? Enter default model name (required for Ollama, see: https://memgpt.readme.io/docs/ollama): hexbenjam
in/memgpt-dpo-uncensored:q8_0
? Select default model wrapper (recommended: chatml): chatml
? Select your model's context window (for Mistral 7B models, this is probably 8k / 8192): 8192
? Select embedding provider: local
? Select default preset: memgpt_chat
? Select default persona: sam_pov
? Select default human: cs_phd
? Select storage backend for archival data: postgres
? Enter postgres connection string (e.g. postgresql+pg8000://{user}:{password}@{ip}:5432/{database}):
postgresql+pg8000://[USERNAME]:[PASSWORD]@[LOCALHOST]:5432/memgpt
? Select storage backend for recall data: postgres
? Enter postgres connection string (e.g. postgresql+pg8000://{user}:{password}@{ip}:5432/{database}):
postgresql+pg8000://[USERNAME]:[PASSWORD]@[LOCALHOST]:5432/memgpt
📖 Saving config to /[USER_DIRECTORY]/.memgpt/config
(pymemgpt-c3VCR-PY-py3.10) [USERNAME]@[HOSTNAME]:~/[DIRECTORY]$ memgpt run
Loading config from /home/[USERNAME]/.memgpt/config

? Would you like to select an existing agent? Yes
? Select agent: [AGENT_NAME]

🔁 Using existing agent [AGENT_NAME]
Loading config from /home/[USERNAME]/.memgpt/config
Loading config from /home/[USERNAME]/.memgpt/config

Hit enter to begin (will request first MemGPT message)

An exception occurred when running agent.step():
Traceback (most recent call last):
  File "/home/[USERNAME]/[DIRECTORY]/MemGPT/memgpt/main.py", line 380, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
  File "/home/[USERNAME]/[DIRECTORY]/MemGPT/memgpt/main.py", line 356, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
  File "/home/[USERNAME]/[DIRECTORY]/MemGPT/memgpt/agent.py", line 793, in step
    raise e
  File "/home/[USERNAME]/[DIRECTORY]/MemGPT/memgpt/agent.py", line 710, in step
    response = self._get_ai_reply(
  File "/home/[USERNAME]/[DIRECTORY]/MemGPT/memgpt/agent.py", line 429, in _get_ai_reply
    raise e
  File "/home/[USERNAME]/[DIRECTORY]/MemGPT/memgpt/agent.py", line 409, in _get_ai_reply
    response = create(
  File "/home/[USERNAME]/[DIRECTORY]/MemGPT/memgpt/llm_api/llm_api_tools.py", line 115, in wrapper
    raise e
  File "/home/[USERNAME]/[DIRECTORY]/MemGPT/memgpt/llm_api/llm_api_tools.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/[USERNAME]/[DIRECTORY]/MemGPT/memgpt/llm_api/llm_api_tools.py", line 235, in create
    return get_chat_completion(
  File "/home/[USERNAME]/[DIRECTORY]/MemGPT/memgpt/local_llm/chat_completion_proxy.py", line 68, in get_chat_completion
    if messages[0]["role"] == "system" and messages[0]["content"].strip() == SUMMARIZE_SYSTEM_MESSAGE.strip():
TypeError: 'Message' object is not subscriptable
? Retry agent.step()? (Y/n) 

 ```

**Screenshots**

**Additional context**

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.
```
(pymemgpt-c3VCR-PY-py3.10) [USERNAME]@[HOSTNAME]:~/[PATH]$ cat ~/.memgpt/config
[defaults]
preset = memgpt_chat
persona = sam_pov
human = cs_phd

[model]
model = hexbenjamin/memgpt-dpo-uncensored:q8_0
model_endpoint = http://localhost:11434
model_endpoint_type = ollama
model_wrapper = chatml
context_window = 8192

[embedding]
embedding_endpoint_type = local
embedding_model = BAAI/bge-small-en-v1.5
embedding_dim = 384
embedding_chunk_size = 300

[archival_storage]
type = postgres
path = /home/[USERNAME]/.memgpt/chroma
uri = postgresql+pg8000://[USERNAME]:[PASSWORD]@localhost:5432/memgpt

[recall_storage]
type = postgres
path = /home/[USERNAME]/.memgpt
uri = postgresql+pg8000://[USERNAME]:[PASSWORD]@localhost:5432/memgpt

[metadata_storage]
type = postgres
path = /home/[USERNAME]/.memgpt
uri = postgresql+pg8000://[USERNAME]:[PASSWORD]@localhost:5432/memgpt

[version]
memgpt_version = 0.3.9

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000
```
---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [x] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
   `hexbenjamin/memgpt-dpo-uncensored:q8_0`
- [x] The local LLM backend you are using (web UI? LM Studio?)
   Ollama
- [x] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)
  Local computer, Windows, no GPU

**Comment by sarahwooders** [comment]
Thanks for this report! I was able to reproduce the issue with Ollama, and pushed the fix to  #1251. Once that's merged, you can install from source or with `pip install -U pymemgpt-nightly` -- but please let me know if you keep having issues.
