### ISSUE TITLE
HTTPError: 500 Server Error

### ISSUE THREAD

**Issue by xz-4396** [cpacker/MemGPT#1295]
At first, it can be successfully run. But after a few times, an HTTP error occurred, either by using the previous agent or by creating a new one.

An exception occurred when running agent.step():
Traceback (most recent call last):
  File "D:\Projects\memGPT\MemGPT\memgpt\main.py", line 395, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\memGPT\MemGPT\memgpt\main.py", line 364, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
                                                                                          ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\memGPT\MemGPT\memgpt\agent.py", line 804, in step
    raise e
  File "D:\Projects\memGPT\MemGPT\memgpt\agent.py", line 719, in step
    response = self._get_ai_reply(
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\memGPT\MemGPT\memgpt\agent.py", line 437, in _get_ai_reply
    raise e
  File "D:\Projects\memGPT\MemGPT\memgpt\agent.py", line 414, in _get_ai_reply
    response = create(
               ^^^^^^^
  File "D:\Projects\memGPT\MemGPT\memgpt\llm_api\llm_api_tools.py", line 88, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\memGPT\MemGPT\memgpt\llm_api\llm_api_tools.py", line 184, in create
    return openai_chat_completions_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\memGPT\MemGPT\memgpt\llm_api\openai.py", line 374, in openai_chat_completions_request
    raise http_err
  File "D:\Projects\memGPT\MemGPT\memgpt\llm_api\openai.py", line 364, in openai_chat_completions_request
    response.raise_for_status()  # Raises HTTPError for 4XX/5XX status
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\APP\conda\miniconda\envs\MemGPT\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions

**Comment by quantumalchemy** [comment]
thought I would bump this .  inference.memgpt.ai on error for 4 days  - reported it on discord a few days ago also
my guess the endpoint has been shutdown since no response  .. to bad.. great while it lasted much appreciated!
