### ISSUE TITLE
Error  :  422 Client Error: Unprocessable Entity when using Deepseek

### ISSUE THREAD

**Issue by bamit99** [cpacker/MemGPT#1419]
I am using Deepseek LLM which is OpenAI compatible. Provided the base URL, Key. It connects but during initialization, it gives the below error.

An exception occurred when running agent.step():
Traceback (most recent call last):
  File "/home/amit/anaconda3/lib/python3.11/site-packages/memgpt/main.py", line 408, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/anaconda3/lib/python3.11/site-packages/memgpt/main.py", line 377, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
                                                                                          ^^^^^^^^^^^^^^^^^^
  File "/home/amit/anaconda3/lib/python3.11/site-packages/memgpt/agent.py", line 818, in step
    raise e
  File "/home/amit/anaconda3/lib/python3.11/site-packages/memgpt/agent.py", line 733, in step
    response = self._get_ai_reply(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amit/anaconda3/lib/python3.11/site-packages/memgpt/agent.py", line 451, in _get_ai_reply
    raise e
  File "/home/amit/anaconda3/lib/python3.11/site-packages/memgpt/agent.py", line 426, in _get_ai_reply
    response = create(
               ^^^^^^^
  File "/home/amit/anaconda3/lib/python3.11/site-packages/memgpt/llm_api/llm_api_tools.py", line 106, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/anaconda3/lib/python3.11/site-packages/memgpt/llm_api/llm_api_tools.py", line 204, in create
    return openai_chat_completions_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/anaconda3/lib/python3.11/site-packages/memgpt/llm_api/openai.py", line 377, in openai_chat_completions_request
    raise http_err
  File "/home/amit/anaconda3/lib/python3.11/site-packages/memgpt/llm_api/openai.py", line 367, in openai_chat_completions_request
    response.raise_for_status()  # Raises HTTPError for 4XX/5XX status
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.deepseek.com/chat/completions

**Comment by scenaristeur** [comment]
no downtime today on deepseek https://status.deepseek.com/

**Comment by cpacker** [comment]
@scenaristeur @bamit99 I'm guessing this is due to DeepSeek not being fully OpenAI compliant (not fully compatible with the spec here https://platform.openai.com/docs/api-reference/chat)? E.g. MemGPT is sending a POST request with function call schemas, meanwhile DeepSeek only allows a subset of types of function calls?

**Comment by bamit99** [comment]
Quite possible. I am a not a coder so I try and do my best to understand. I did try running it with ChatGPT. It failed with 3.5, 4.0 with 16K but worked with the newest GPT4 model. Seems, it is very specific about configs related to LLMs

**Comment by bamit99** [comment]
By the way, this is the link from Deepseek for chat completion. Reason, I use this is because it is dirt cheap and is sufficient for the kind of AI exploration that I do! :)

https://platform.deepseek.com/api-docs/api/create-chat-completion/

**Comment by quantumcthulhu** [comment]
How do you use DeepSeek with Letta?
I try different ways, but still does not work for me

OPENAI_API_BASE="https://api.deepseek.com/" OPENAI_API_KEY="sk-..." letta server

**Comment by indiejoseph** [comment]
beside of provide define "OPENAI_API_BASE" and "OPENAI_API_KEY", you should also have the correct model name eg: deepseek-chat when calling the API endpoint, that's probably have to alter the model handling code: https://github.com/letta-ai/letta/blob/main/letta/schemas/llm_config_overrides.py
