### ISSUE TITLE
[[inference.memgpt.ai is down]] server error 524 , https://inference.memgpt.ai/chat/completions does not respond to requests

### ISSUE THREAD

**Issue by scenaristeur** [cpacker/MemGPT#1420]
![image](https://github.com/cpacker/MemGPT/assets/4020744/6c994714-32d3-4dcd-9f5d-71fe69050a6e)

since a couple of hour (i worked well before) i got this error with `m̀emgpt run` and same thing occurs with `memgpt serve 

error 524 seems to come from the server url: https://inference.memgpt.ai/chat/completions which does not seem to respond

same error with the latest commit 

```
 git pull --rebase
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 47 (delta 22), reused 20 (delta 11), pack-reused 0
Dépaquetage des objets: 100% (47/47), 19.00 Kio | 810.00 Kio/s, fait.
Depuis https://github.com/cpacker/MemGPT
   e8eed7b..8d7ac83  main       -> origin/main
```

```
memgpt run 

? Would you like to select an existing agent? No

🧬 Creating new agent...
->  🤖 Using persona profile: 'sam_pov'
->  🧑 Using human profile: 'basic'
🎉 Created new agent 'GloriousRacquet' (id=c1c6c393-1fe5-4767-80fc-5b328df92cb3)

Hit enter to begin (will request first MemGPT message)
salut

An exception occurred when running agent.step(): 
Traceback (most recent call last):
  File "/home/smag/dev/quest/bot/MemGPT/memgpt/main.py", line 408, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
  File "/home/smag/dev/quest/bot/MemGPT/memgpt/main.py", line 377, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
  File "/home/smag/dev/quest/bot/MemGPT/memgpt/agent.py", line 818, in step
    raise e
  File "/home/smag/dev/quest/bot/MemGPT/memgpt/agent.py", line 733, in step
    response = self._get_ai_reply(
  File "/home/smag/dev/quest/bot/MemGPT/memgpt/agent.py", line 451, in _get_ai_reply
    raise e
  File "/home/smag/dev/quest/bot/MemGPT/memgpt/agent.py", line 426, in _get_ai_reply
    response = create(
  File "/home/smag/dev/quest/bot/MemGPT/memgpt/llm_api/llm_api_tools.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "/home/smag/dev/quest/bot/MemGPT/memgpt/llm_api/llm_api_tools.py", line 209, in create
    return openai_chat_completions_request(
  File "/home/smag/dev/quest/bot/MemGPT/memgpt/llm_api/openai.py", line 377, in openai_chat_completions_request
    raise http_err
  File "/home/smag/dev/quest/bot/MemGPT/memgpt/llm_api/openai.py", line 367, in openai_chat_completions_request
    response.raise_for_status()  # Raises HTTPError for 4XX/5XX status
  File "/home/smag/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 524 Server Error:  for url: https://inference.memgpt.ai/chat/completions
? Retry agent.step()? (Y/n)
```

**Comment by scenaristeur** [comment]
seems very similar to https://github.com/cpacker/MemGPT/issues/1419, but on another endpoint

**Comment by sarahwooders** [comment]
This should be back up now - sorry we keep having to re-start the endpoint for various reasons...

**Comment by scenaristeur** [comment]
sounds ok 
![image](https://github.com/cpacker/MemGPT/assets/4020744/e16ea3e4-6299-48f8-88a1-a7fc4f2d27e8)
thxs
Do you know what are the limitation usage of https://inference.memgpt.ai/chat/completions ?

**Comment by scenaristeur** [comment]
Do you know what are the limitation usage of https://inference.memgpt.ai/chat/completions ?
