### ISSUE TITLE
sqlite3.OperationalError: no such column: agents.system

### ISSUE THREAD

**Issue by scenaristeur** [cpacker/MemGPT#1501]
**Describe the bug**
I want to install from source according to https://memgpt.readme.io/docs/contributing#installing-memgpt-from-source

i have tried with pip or poetry but i have this errors : 

```
Installing the current project: pymemgpt (0.3.18)
(pymemgpt-py3.11) :~/dev/MemGPT$ memgpt run
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/pymemgpt-IUEEElC1-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/user/.cache/pypoetry/virtualenvs/pymemgpt-IUEEElC1-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: agents.system

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/pymemgpt-IUEEElC1-py3.11/bin/memgpt", line 6, in <module>
    sys.exit(app())

[...]

    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: agents.system
[SQL: SELECT agents.id AS agents_id, agents.user_id AS agents_user_id, agents.name AS agents_name, agents.system AS agents_system, agents.created_at AS agents_created_at, agents.llm_config AS agents_llm_config, agents.embedding_config AS agents_embedding_config, agents.state AS agents_state, agents._metadata AS agents__metadata, agents.tools AS agents_tools 
FROM agents 
WHERE agents.user_id = ?]
[parameters: ('00000000-0000-0000-0000-000000000000',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

``

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt`? `pip install pymemgpt-nightly`? `git clone`?
- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by sarahwooders** [comment]
Did you already have existing agents before installing from source? We recently changed the schema and haven't added automated migrations yet. If you're ok with losing data, you can re-set your database with `rm ~/.memgpt/sqlite.db`. Otherwise, we'll probably release a migration script on the next release.
