### ISSUE TITLE
can not create / read preset, nor functions

### ISSUE THREAD

**Issue by scenaristeur** [cpacker/MemGPT#1543]
using 0.3.19

I can : memgpt run

according to https://memgpt.readme.io/docs/functions
but can't add preset

```

memgpt add preset -f ~/.memgpt/presets/memgpt_extras.yaml --name extra
MemGPT.memgpt.server.server - INFO - loading configuration from '/home/smag/.memgpt/config'
Traceback (most recent call last):
  File "/home/smag/dev/MemGPT/.venv/bin/memgpt", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/home/smag/dev/MemGPT/.venv/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/smag/dev/MemGPT/.venv/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smag/dev/MemGPT/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smag/dev/MemGPT/.venv/lib/python3.11/site-packages/typer/core.py", line 783, in main
    return _main(
           ^^^^^^
  File "/home/smag/dev/MemGPT/.venv/lib/python3.11/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/smag/dev/MemGPT/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smag/dev/MemGPT/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smag/dev/MemGPT/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smag/dev/MemGPT/.venv/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smag/dev/MemGPT/memgpt/cli/cli_config.py", line 1211, in add
    raise ValueError(f"Unknown kind {option}")
ValueError: Unknown kind preset
```

 memgpt list presets
gives me 

```
Usage: memgpt list [OPTIONS] ARG:{agents|humans|personas|sources}
Try 'memgpt list --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Invalid value for 'ARG:{agents|humans|personas|sources}': 'presets' is not   │
│ one of 'agents', 'humans', 'personas', 'sources'.                            │
╰──────────────────────────────────────────────────────────────────────────────╯
```
when i manually change it in config 

```
[defaults]
preset = memgpt_extras
persona = sam_pov
human = basic
```
i got an error looking for a system_prompt and not a preset at .memgpt/system_prompts/memgpt_extras.txt

```
  File "/home/smag/.local/lib/python3.10/site-packages/memgpt/prompts/gpt_system.py", line 26, in get_system_text
    raise FileNotFoundError(f"No file found for key {key}, path={file_path}")
FileNotFoundError: No file found for key memgpt_extras, path=/home/smag/.memgpt/system_prompts/memgpt_extras.txt
```

when i try to add d20_roll in the server ui 

```
INFO:     127.0.0.1:52450 - "GET /api/tools HTTP/1.1" 200 OK
INFO:     127.0.0.1:48964 - "POST /api/tools HTTP/1.1" 422 Unprocessable Entity

``

**Comment by sarahwooders** [comment]
We actually just modified the way to add custom tools to MemGPT (no more presets) - you can see the updated docs here: https://memgpt.readme.io/docs/adding-custom-tools-to-memgpt

Let us know if you still have issues with the new tool creation workflow!

**Comment by scenaristeur** [comment]
@sarahwooders how could i access http_request  or read/write file from https://github.com/cpacker/MemGPT/blob/main/memgpt/functions/function_sets/extras.py ?

they are not available in ui 

![image](https://github.com/user-attachments/assets/cde8ba2f-f887-4cc9-9b04-31a2b5962ecb)

**Comment by tm-robinson** [comment]
I am also getting 422 Unprocessable Entity in the logs when trying to add a new tool via the UI.  I think this is because the UI creates a REST call which does not include the `json_schema` parameter which is now mandatory as part of the `CreateToolRequest` pydantic model.

Request:

```
{
    "name": "roll_d20",
    "source_code": "import random\n\ndef roll_d20(self) -> str:\n    \"\"\"\n    Simulate the roll of a 20-sided die (d20).\n\n    This function generates a random integer between 1 and 20, inclusive,\n    which represents the outcome of a single roll of a d20.\n\n    Returns:\n        int: A random integer between 1 and 20, representing the die roll.\n\n    Example:\n        >>> roll_d20()\n        15  # This is an example output and may vary each time the function is called.\n    \"\"\"\n    dice_role_outcome = random.randint(1, 20)\n    output_string = f\"You rolled a {dice_role_outcome}\"\n    return output_string"
}
```

Response:

```
{
    "detail": [
        {
            "type": "missing",
            "loc": [
                "body",
                "json_schema"
            ],
            "msg": "Field required",
            "input": {
                "name": "roll_d20",
                "source_code": "import random\n\ndef roll_d20(self) -> str:\n    \"\"\"\n    Simulate the roll of a 20-sided die (d20).\n\n    This function generates a random integer between 1 and 20, inclusive,\n    which represents the outcome of a single roll of a d20.\n\n    Returns:\n        int: A random integer between 1 and 20, representing the die roll.\n\n    Example:\n        >>> roll_d20()\n        15  # This is an example output and may vary each time the function is called.\n    \"\"\"\n    dice_role_outcome = random.randint(1, 20)\n    output_string = f\"You rolled a {dice_role_outcome}\"\n    return output_string"
            },
            "url": "https://errors.pydantic.dev/2.7/v/missing"
        }
    ]
}
```

**Comment by Lorodn4x** [comment]
Has anyone been able to add a tool?

**Comment by sarahwooders** [comment]
Please check the latest documentation at https://docs.letta.com/agents/tools -- there's been a lot of changes to how tools are added to try to simply the process (eliminating the need for files, presets, etc.) 

If that doesn't work please re-open this issue.
