### ISSUE TITLE
 if msg.role == "assistant" and len(msg.tool_calls) >= 1: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by akwin1234** [cpacker/MemGPT#1572]
**Describe the bug**

INFO:     ::1:54745 - "GET /api/agents/d10fb9cb-2e4d-46d8-9b18-c53efc227bef/memory HTTP/1.1" 200 OK
Task exception was never retrieved
future: <Task finished name='Task-54' coro=<to_thread() done, defined at C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\threads.py:12> exception=TypeError("object of type 'NoneType' has no len()")>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\server\server.py", line 602, in user_message
    usage = self._step(user_id=user_id, agent_id=agent_id, input_message=packaged_user_message, timestamp=timestamp)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\server\server.py", line 391, in _step
    new_messages, heartbeat_request, function_failed, token_warning, usage = memgpt_agent.step(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 739, in step
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 651, in step
    response = self._get_ai_reply(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 348, in _get_ai_reply
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 321, in _get_ai_reply
    response = create(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 223, in wrapper
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 196, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 338, in create
    response = unpack_inner_thoughts_from_kwargs(response=response, inner_thoughts_key=INNER_THOUGHTS_KWARG)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 96, in unpack_inner_thoughts_from_kwargs
    if msg.role == "assistant" and len(msg.tool_calls) >= 1:
TypeError: object of type 'NoneType' has no len()
Task exception was never retrieved
future: <Task finished name='Task-60' coro=<to_thread() done, defined at C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\threads.py:12> exception=TypeError("object of type 'NoneType' has no len()")>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\server\server.py", line 602, in user_message
    usage = self._step(user_id=user_id, agent_id=agent_id, input_message=packaged_user_message, timestamp=timestamp)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\server\server.py", line 391, in _step
    new_messages, heartbeat_request, function_failed, token_warning, usage = memgpt_agent.step(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 739, in step
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 651, in step
    response = self._get_ai_reply(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 348, in _get_ai_reply
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 321, in _get_ai_reply
    response = create(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 223, in wrapper
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 196, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 338, in create
    response = unpack_inner_thoughts_from_kwargs(response=response, inner_thoughts_key=INNER_THOUGHTS_KWARG)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\llm_api\llm_api_tools.py", line 96, in unpack_inner_thoughts_from_kwargs
    if msg.role == "assistant" and len(msg.tool_calls) >= 1:
TypeError: object of type 'NoneType' has no len()

**Please describe your setup**
- [x] How did you install memgpt?
  - `pip install pymemgpt`
- [x] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  - How are you running `memgpt`? Powershell

**Screenshots**

**Additional context**

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.
"""
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = gpt-4o
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 262144

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-3-large
embedding_dim = 4090
embedding_chunk_size = 2045

[archival_storage]
type = chroma
path = C:\Users\user\.memgpt\chroma

[recall_storage]
type = sqlite
path = C:\Users\user\.memgpt
uri = ../

[metadata_storage]
type = sqlite
path = C:\Users\user\.memgpt
uri = ../

[version]
memgpt_version = 0.3.20

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000

"""
---
Using open AI. 

when i type message to ai like HI

i get the error above

**Comment by sarahwooders** [comment]
Thanks for the report! We'll merge a fix soon.
