### ISSUE TITLE
AttributeError: 'AgentState' object has no attribute 'state' AND other weird behavior

### ISSUE THREAD

**Issue by NovaBro** [cpacker/MemGPT#1801]
**Describe the bug**
1. When I run "letta run" and select a previous agent through the CLI, I get the error "AttributeError: 'AgentState' object has no attribute 'state'"
2. When I create an agent through the CLI, I cannot find it on the ADE. When I create an agent on the ADE, I cannot see it through the CLI

**Please describe your setup**

Installation
1. I have created a python 3.12 virtual environment
2. I then did pip install letta 
3. Followed the quickstart guide

Setup
1. macOS 14.6.1, m1 chip, 
2. VSCODE
3. Running letta though terminal
4. Tried running the python stuff mentioned, but that has not worked for me either, (i assume that once this issue is fixed the python stuff will then work, one problem at a time)

**Screenshots**
letta not showing up on both systems:
<img width="1385" alt="Screenshot 2024-09-29 at 3 21 44 PM" src="https://github.com/user-attachments/assets/7f3c91d6-abb3-4c42-95f3-b51db0d0b215">
<img width="835" alt="Screenshot 2024-09-29 at 3 22 02 PM" src="https://github.com/user-attachments/assets/5fbd0618-d944-4c92-978b-8ea6ec0d3e4e">
<img width="611" alt="Screenshot 2024-09-29 at 3 22 51 PM" src="https://github.com/user-attachments/assets/1fddc5ef-b5c5-45fe-9384-e77758a17ea6">

**Letta Config**
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = memgpt-openai
model_endpoint = https://inference.memgpt.ai
model_endpoint_type = openai
context_window = 8192

[embedding]
embedding_endpoint_type = hugging-face
embedding_endpoint = https://embeddings.memgpt.ai
embedding_model = BAAI/bge-large-en-v1.5
embedding_dim = 1024
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /Users/williamzheng/.letta/chroma

[recall_storage]
type = sqlite
path = /Users/williamzheng/.letta

[metadata_storage]
type = sqlite
path = /Users/williamzheng/.letta

[version]
letta_version = 0.1.16

[client]
anon_clientid = user-e15c337c-32fd-4fd5-a6be-10e7e3b86f35

---

**Local LLM details**
Unsure how to find the following information, if you need them please advise on how to get them:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by NovaBro** [comment]
Here is the full error message: 

(my_letta) (base) williamzheng@Williams-MacBook-Pro-258 MemGPT_Letta % letta run

? Would you like to select an existing agent? Yes
? Select agent: PassionateKitten

🔁 Using existing agent PassionateKitten
Traceback (most recent call last):
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/bin/letta", line 10, in <module>
    sys.exit(app())
             ^^^^^
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/typer/core.py", line 783, in main
    return _main(
           ^^^^^^
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/letta/cli/cli.py", line 495, in run
    printd("Agent state:", agent_state.state)
                           ^^^^^^^^^^^^^^^^^
  File "/Users/williamzheng/Documents/UmichFolder/2025 Fall Semester /Research 499/MemGPT_Letta/my_letta/lib/python3.12/site-packages/pydantic/main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'AgentState' object has no attribute 'state'

**Comment by sarahwooders** [comment]
I believe this error was recently fixed https://github.com/cpacker/MemGPT/blob/main/letta/cli/cli.py#L495 

Could you please try with the nightly version `pip install letta-nightly`, and let me know if you are still facing issues? 

Thanks

**Comment by NovaBro** [comment]
Thank you for your response!
What is letta-nightly?
I have just downloaded it into my venv (forgot to mention I am using a virtual environment).
I am now able to reload previous models. Additionally, I am now able to view my agents locally and on the (http://localhost:8283/agents).

Additionally, I was wondering, where are the agents actually stored? the file ./letta/agents is empty.

**Comment by sarahwooders** [comment]
`letta-nightly` is a package with the latest code on main, so you can use the code fixes before we release. 

The agents are stored in the database (we need to get rid of `./letta/agents`), so either in postgres or `./letta/sqlite.db`.

**Comment by NovaBro** [comment]
Thank you!
