### ISSUE TITLE
Broken `letta configure`

### ISSUE THREAD

**Issue by sarahwooders** [cpacker/MemGPT#1836]
```
Please help me,thanks
letta configure
? Select LLM inference provider: local
? Select LLM backend (select 'openai' if you have an OpenAI compatible proxy): groq
? Enter default endpoint: https://api.groq.com/openai
? Enter your Groq API key: **
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/bin/letta", line 8, in <module>
    sys.exit(app())
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/typer/main.py", line 328, in call
    raise e
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/typer/main.py", line 311, in call
    return getcommand(self)(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1157, in _call
    return self.main(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/typer/core.py", line 783, in main
    return _main(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/letta/cli/cli_config.py", line 1016, in configure
    model, model_wrapper, context_window = configure_model(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/letta/cli/cli_config.py", line 632, in configure_model
    valid_model = config.default_llm_config.model in model_options
AttributeError: 'NoneType' object has no attribute 'model'
```

**Comment by quantumalchemy** [comment]
Also broken for local api openapi custom endpoin and llama.cpp
letta configure
? Select LLM inference provider: local
? Select LLM backend (select 'openai' if you have an OpenAI compatible proxy): llamacpp
? Enter default endpoint: http://llamafile:8666
? Is your LLM endpoint authenticated? (default no) No
? Select default model wrapper (recommended: chatml): llama3
? Select your model's context window (for Mistral 7B models, this is probably 8k / 8192): 8192
? Select embedding provider: hugging-face
? Enter default endpoint: https://embeddings.memgpt.ai
? Enter HuggingFace model tag (e.g. BAAI/bge-large-en-v1.5): BAAI/bge-large-en-v1.5
? Enter embedding model dimentions (e.g. 1024): 1024
? Select storage backend for archival data: chroma
? Select chroma backend: persistent
? Select storage backend for recall data: sqlite
Traceback (most recent call last):
  File "/usr/local/bin/letta", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/core.py", line 783, in main
    return _main(
           ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/letta/cli/cli_config.py", line 1043, in configure
    default_llm_config=LLMConfig(
                       ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for LLMConfig
model
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type

**Comment by norzog** [comment]
I am getting this same error. I looked into the code and it looks like it is already on the todo list. any chance of moving this up? Im attempting a fix but I am an amateur at best and help would be appreciated.  

    # TODO: remove most of this (deplicated with User table)
    config = LettaConfig(
        default_llm_config=LLMConfig(
            model=model,
            model_endpoint=model_endpoint,
            model_endpoint_type=model_endpoint_type,
            model_wrapper=model_wrapper,
            context_window=context_window,
        ),
        default_embedding_config=EmbeddingConfig(
            embedding_endpoint_type=embedding_endpoint_type,
            embedding_endpoint=embedding_endpoint,
            embedding_dim=embedding_dim,
            embedding_model=embedding_model,

**Comment by sarahwooders** [comment]
Command was deprecated in 0.5.0
