### ISSUE TITLE
Blocker - Editing block (human or persona) throws 500 internal error - Runs in to Recursive loop

### ISSUE THREAD

**Issue by raolak** [cpacker/MemGPT#1925]
**Describe the bug**
When one edits either Human or persona, api throws 500 internal server error.

This issue occurs due to a recursive loop caused by the way you are trying to set the label field inside the ensure_label function. Each time self.label = self.name is called, it triggers the __setattr__ method, which causes an infinite recursion.

Server log
uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/.venv/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/app/.venv/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 264, in app
    solved_result = await solve_dependencies(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 620, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 750, in request_body_to_args
    v_, errors_ = field.validate(value, values, loc=loc)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/fastapi/_compat.py", line 125, in validate
    self._type_adapter.validate_python(value, from_attributes=True),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 366, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/letta/schemas/block.py", line 45, in ensure_label
    self.label = self.name
    ^^^^^^^^^^
  File "/letta/schemas/block.py", line 53, in __setattr__
    super().__setattr__(name, value)
  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 881, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
  File "/letta/schemas/block.py", line 45, in ensure_label
    self.label = self.name
    ^^^^^^^^^^
  File "/letta/schemas/block.py", line 53, in __setattr__
    super().__setattr__(name, value)
  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 881, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
  File "/letta/schemas/block.py", line 45, in ensure_label
    self.label = self.name
    ^^^^^^^^^^
  File "/letta/schemas/block.py", line 53, in __setattr__
    super().__setattr__(name, value)
  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 881, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
  File "/letta/schemas/block.py", line 45, in ensure_label
    self.label = self.name
    ^^^^^^^^^^
  ..... recursive loop

Api call
Patch- <letta server>/v1/blocks/block-f392c76c-6589-4a78-a7ba-dc5ded679d77
Payload
{
    "id": "block-f392c76c-6589-4a78-a7ba-dc5ded679d77",
    "value": "Name: Lnr1"
}

Response
500 Internal Server Error
Internal Server Error

**Please describe your setup**
- [ ] How did you install letta?
  - Installed letta server using docker in k8s

**Comment by sarahwooders** [comment]
What version are you using? I remember seeing this bug before but added a fix, and I was able to edit the human without issue in the ADE for 0.5.1.

**Comment by raolak** [comment]
I am using following version
{"version":"0.4.1","status":"ok"}

Can you please tell me what is the branch from which I need to do docker
build? Is it the *main* branch or any specific other stable branch?

-lnr

**Comment by sarahwooders** [comment]
Could you please run `docker pull lettaai/letta:latest`? You might have an older version of the image. If you are building docker container from source, you can do it on `main` but the releases are what we expect to be stable.

**Comment by raolak** [comment]
Thanks for the update Sarah .

I did that , but in  microk8s it throws image pull back error with arch
compatibility issue . I am deploying in k8s. The last time I built the
docker was from main . Shall I use release tag and build for now to test ?

_lnr
jnaa.tech
