### ISSUE TITLE
WebUI fails to update Agent and Persona templates

### ISSUE THREAD

**Issue by stracker-phil** [cpacker/MemGPT#1931]
**Describe the bug**

In a fresh installation: Open the web UI, editing "User Templates" (or "Agent Templates") ends in a server error.

> Error: `RecursionError: maximum recursion depth exceeded while calling a Python object`

I've tested the behavior via the `pip install letta` and the Docker setup. Both setups throw the same error.

---

**Please describe your setup**
- [x] How did you install letta?
  - `pip install letta` (python 3.11 via miniconda)
  - `git clone ... docker compose up`
- [x] Describe your setup
  - OS: macOS 15 / M2 Pro (Silicon)
  - Usage: Terminal (zsh) using `conda activate memgpt-env && letta server`

---

**Screenshots**

[](https://github.com/user-attachments/assets/1bd544e1-1f59-4523-ae08-3f0c17ae4d0f)

**Additional context**

<details>
<summary><strong>Full console output</strong></summary>

```
INFO:     ::1:55934 - "PATCH /v1/blocks/block-ac9028a5-6276-4c07-987d-683bab68edad HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 658, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 890, in request_body_to_args
    v_, errors_ = _validate_value_with_model_field(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 698, in _validate_value_with_model_field
    v_, errors_ = field.validate(value, values, loc=loc)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/fastapi/_compat.py", line 128, in validate
    self._type_adapter.validate_python(value, from_attributes=True),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/pydantic/type_adapter.py", line 366, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/letta/schemas/block.py", line 45, in ensure_label
    self.label = self.name
    ^^^^^^^^^^

...

  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/letta/schemas/block.py", line 53, in __setattr__
    super().__setattr__(name, value)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/pydantic/main.py", line 881, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/letta/schemas/block.py", line 45, in ensure_label
    self.label = self.name
    ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/letta/schemas/block.py", line 53, in __setattr__
    super().__setattr__(name, value)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/pydantic/main.py", line 881, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/letta/schemas/block.py", line 45, in ensure_label
    self.label = self.name
    ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/letta/schemas/block.py", line 53, in __setattr__
    super().__setattr__(name, value)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/pydantic/main.py", line 881, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/letta/schemas/block.py", line 45, in ensure_label
    self.label = self.name
    ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/letta/schemas/block.py", line 53, in __setattr__
    super().__setattr__(name, value)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/pydantic/main.py", line 864, in __setattr__
    elif not _fields.is_valid_field_name(name):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt-env/lib/python3.11/site-packages/pydantic/_internal/_fields.py", line 329, in is_valid_field_name
    return not name.startswith('_')
               ^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
```

</details>

**Letta Config**
Please attach your `~/.letta/config` file or copy past it below.

<details>
<summary><strong>letta/config</strong></summary>

```
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[archival_storage]
type = chroma
path = /Users/philipp/.letta/chroma

[recall_storage]
type = sqlite
path = /Users/philipp/.letta

[metadata_storage]
type = sqlite
path = /Users/philipp/.letta

[version]
letta_version = 0.5.0

[client]
anon_clientid = user-00000000


```

</details>

**Comment by stracker-phil** [comment]
Note: This issue is the same as the one described in #1925
