### ISSUE TITLE
Requesting Response in Markdown Causes Unexpected Application Error

### ISSUE THREAD

**Issue by davidsells** [cpacker/MemGPT#1952]
## System Information
* MacOS Version: 14.5
* Letta Image: lettaai/letta:0.5.1

## Agent Configuration
* Agent test
* Model: letta-free
* Agent Persona: sam_pov
* Human Persona: basic

## Chat Request ( simplified for testing )
Please convert this to Markdown: test

1 test
## System Response

Unexpected Application Error!
Cannot assign to read only property '0' of string 'test 1. test '
TypeError: Cannot assign to read only property '0' of string 'test

1. test
'
    at code (http://localhost:8083/assets/index-d6b3669a.js:204:14984)
    at RC (http://localhost:8083/assets/index-d6b3669a.js:38:19538)
    at AF (http://localhost:8083/assets/index-d6b3669a.js:40:44055)
    at kF (http://localhost:8083/assets/index-d6b3669a.js:40:39787)
    at gV (http://localhost:8083/assets/index-d6b3669a.js:40:39715)
    at Eg (http://localhost:8083/assets/index-d6b3669a.js:40:39568)
    at y1 (http://localhost:8083/assets/index-d6b3669a.js:40:35933)
    at wF (http://localhost:8083/assets/index-d6b3669a.js:40:34882)
    at k (http://localhost:8083/assets/index-d6b3669a.js:25:1547)
    at MessagePort.D (http://localhost:8083/assets/index-d6b3669a.js:25:1906)

## Additional Information
The agent is now unusable.  I do not see any way to rectify the situation. Additionally there appears to be no  way to delete the corrupted agent.

**Comment by RemingtonWimberly** [comment]
I have the same issue any time I ask my agent to return how much things cost.
![image](https://github.com/user-attachments/assets/5a58e5e7-c9f8-4ff4-9222-868f6fb44324)

**Comment by mattzh72** [comment]
Should be fixed by the above PR
