### ISSUE TITLE
Cannot configure or run with Azure OpenAI

### ISSUE THREAD

**Issue by leloss** [cpacker/MemGPT#229]
It looks like the configuration sticks to "openai" no matter how hard I try to use "azure". Even after hardcode setting all config variables to the Azure OpenAI environment, api_requestor.py stills calls openai.openai_response.OpenAIResponse. 

Version:
memgpt                  0.1.0
openai                  0.28.1

```
│ /lib/python3.10/site-packages/openai/api_requestor.py:775 in                  │
│ _interpret_response_line                                                                         │
│                                                                                                  │
│   772 │   │   # to better handle the "error while streaming" case.                               │
│   773 │   │   stream_error = stream and "error" in resp.data                                     │
│   774 │   │   if stream_error or not 200 <= rcode < 300:                                         │
│ ❱ 775 │   │   │   raise self.handle_error_response(                                              │
│   776 │   │   │   │   rbody, rcode, resp.data, rheaders, stream_error=stream_error               │
│   777 │   │   │   )                                                                              │
│   778 │   │   return resp                                                                        │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │         data = {                                                                             │ │
│ │                │   'error': {                                                                │ │
│ │                │   │   'message': 'Incorrect API key provided:                               │ │
│ │                3********************1db7. You can find your '+56,                     │ │
│ │                │   │   'type': 'invalid_request_error',                                      │ │
│ │                │   │   'param': None,                                                        │ │
│ │                │   │   'code': 'invalid_api_key'                                             │ │
│ │                │   }                                                                         │ │
│ │                }                                                                             │ │
│ │        rbody = '{\n    "error": {\n        "message": "Incorrect API key provided:           │ │
│ │                3************'+202                                                          │ │
│ │        rcode = 401                                                                           │ │
│ │         resp = <openai.openai_response.OpenAIResponse object at 0x7fa7bc91da80>              │ │
│ │     rheaders = <CIMultiDictProxy('Date': 'Tue, 31 Oct 2023 22:58:00 GMT', 'Content-Type':    │ │
│ │                'application/json; charset=utf-8', 'Content-Length': '282', 'Connection':     │ │
│ │                'keep-alive', 'Vary': 'Origin', 'x-request-id':                               │ │
│ │                '8*************************************a', 'strict-transport-security':              │ │
│ │                'max-age=15724800; includeSubDomains', 'CF-Cache-Status': 'DYNAMIC',          │ │
│ │                'Server': 'cloudflare', 'CF-RAY': '81ef800f997305ec-IAD', 'alt-svc':          │ │
│ │                'h3=":443"; ma=86400')>                                                       │ │
│ │         self = <openai.api_requestor.APIRequestor object at 0x7fa7bc91d600>                  │ │
│ │       stream = False                                                                         │ │
│ │ stream_error = False                                                                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AuthenticationError: Incorrect API key provided: 3*****************************7. You can find your API key at
https://platform.openai.com/account/api-keys.
```

**Comment by sarahwooders** [comment]
Can you upgrade to the most recent version of MemGPT with `pip install --upgrade pymemgpt`, and run `memgpt run`?

**Comment by leloss** [comment]
Hi @sarahwooders , Thanks for the tip... 
Versions are now:
pymemgpt                  0.1.16
openai                    0.28.1

Configuration of the Azure openai variables went through smoothly this time, but when I do "memgpt run", the following error occurs:

```
$ memgpt run
Creating new agent...
Created new agent agent_1.
Hit enter to begin (will request first MemGPT message)

step() failed
user_message = None
error = Unrecognized request argument supplied: functions
Unrecognized request argument supplied: functions
An exception ocurred when running agent.step():
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/memgpt/main.py", line 526, in run_agent_loop
    ) = await memgpt_agent.step(user_message, first_message=False, skip_verify=no_verify)
  File "/lib/python3.10/site-packages/memgpt/agent.py", line 1084, in step
    raise e
  File "/lib/python3.10/site-packages/memgpt/agent.py", line 1020, in step
    response = await get_ai_reply_async(model=self.model, message_sequence=input_message_sequence, functions=self.functions)
  File "/lib/python3.10/site-packages/memgpt/agent.py", line 160, in get_ai_reply_async
    raise e
  File "/lib/python3.10/site-packages/memgpt/agent.py", line 141, in get_ai_reply_async
    response = await acreate(
  File "/lib/python3.10/site-packages/memgpt/openai_tools.py", line 115, in wrapper
    raise e
  File "/lib/python3.10/site-packages/memgpt/openai_tools.py", line 95, in wrapper
    return await func(*args, **kwargs)
  File "/lib/python3.10/site-packages/memgpt/openai_tools.py", line 135, in acompletions_with_backoff
    return await openai.ChatCompletion.acreate(**kwargs)
  File "/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 219, in acreate
    response, _, api_key = await requestor.arequest(
  File "/lib/python3.10/site-packages/openai/api_requestor.py", line 384, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "/lib/python3.10/site-packages/openai/api_requestor.py", line 738, in _interpret_async_response
    self._interpret_response_line(
  File "/lib/python3.10/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: functions
? Retry agent.step()? (Y/n)
```

Thanks for your help.

**Comment by sarahwooders** [comment]
@cpacker have you seen this error before?

**Comment by cpacker** [comment]
@leloss @sarahwooders  you have to use an Azure endpoint that allows functions. There's another github issue that talks about this, let me find it.

**Comment by cpacker** [comment]
@leloss see #91 for the solution

**Comment by cpacker** [comment]
@sarahwooders updated the README as well https://github.com/cpacker/MemGPT/tree/main#azure
