### ISSUE TITLE
Can't run MemGPT with LMStudio... Everything broke down...

### ISSUE THREAD

**Issue by ProjCRys** [cpacker/MemGPT#234]
Okay, first I tried setting up my venv to run MemGPT so I got this:
run.bat
@echo off
setlocal

:: Set the path to your Python 3.10.0 installation
set PYTHON_PATH=C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\python.exe

:: Set the path to the directory where you want to create the virtual environment
set VENV_DIR=D:\AI\ChatBots\MemGPT_Setup\venv

:: Set the environment variables
set OPENAI_API_BASE=http://localhost:1234
set BACKEND_TYPE=lmstudio

:: Create and activate the virtual environment
%PYTHON_PATH% -m venv %VENV_DIR%
call %VENV_DIR%\Scripts\activate

:: Run your Python script with the environment variables set
set PYTHONPATH=%PYTHONPATH%;%VENV_DIR%\Lib\site-packages
python MemGPT/main.py

:: Deactivate the virtual environment
deactivate

endlocal

Error:
Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\main.py", line 1, in <module>
    from memgpt.main import app
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\main.py", line 16, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'

I pip installed prettytable but didn't change anything.

- - - - -
So then I tried calling python main.py and this is what I got.

D:\AI\ChatBots\MemGPT_Setup\MemGPT>python main.py
Warning: Running legacy run command. Run `memgpt run` instead.
? Continue with legacy CLI? Yes
⚙️ Found saved config file.
? Use most recent config file 'C:\Users\ADMIN\.memgpt\configs\2023-10-30_08_25_34_AM_PDT-0700.json'? Yes
Running... [exit by typing '/exit', list available commands with '/help']
💭 Bootup sequence complete. Persona activated. Testing messaging functionality.
? Load in saved agent 'C:\Users\ADMIN\.memgpt\saved_state\2023-10-30_09_07_01_AM_PDT-0700.json'? Yes
Loaded checkpoint C:\Users\ADMIN\.memgpt\saved_state\2023-10-30_09_07_01_AM_PDT-0700.json
/load warning: loading persistence manager from C:\Users\ADMIN\.memgpt\saved_state\2023-10-30_09_07_01_AM_PDT-0700.persistence.pickle failed with: Ran out of input
Hit enter to begin (will request first MemGPT message)
[A[K
{'content': '{"status": "OK", "message": null, "time": "2023-10-30 09:04:29 AM '
            'PDT-0700"}',
 'name': 'send_message',
 'role': 'function'}
Warning: no wrapper specified for local LLM, using the default wrapper
step() failed
user_message = None
error = 'choices'
'choices'
An exception ocurred when running agent.step():
Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\main.py", line 524, in run_agent_loop
    ) = await memgpt_agent.step(user_message, first_message=False, skip_verify=no_verify)
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\agent.py", line 1013, in step
    raise e
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\agent.py", line 958, in step
    response = await get_ai_reply_async(model=self.model, message_sequence=input_message_sequence, functions=self.functions)
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\agent.py", line 159, in get_ai_reply_async
    raise e
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\agent.py", line 140, in get_ai_reply_async
    response = await acreate(
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\openai_tools.py", line 102, in wrapper
    raise e
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\openai_tools.py", line 82, in wrapper
    return await func(*args, **kwargs)
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\openai_tools.py", line 111, in acompletions_with_backoff
    return await get_chat_completion(**kwargs)
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\local_llm\chat_completion_proxy.py", line 52, in get_chat_completion
    result = get_lmstudio_completion(prompt)
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\local_llm\lmstudio\api.py", line 42, in get_lmstudio_completion
    result = result["choices"][0]["message"]["content"]
KeyError: 'choices'
? Retry agent.step()? Yes

- - - - -
I then also tried creating a new agent which led to this...
D:\AI\ChatBots\MemGPT_Setup\MemGPT>python main.py
Warning: Running legacy run command. Run `memgpt run` instead.
? Continue with legacy CLI? Yes
⚙️ Found saved config file.
? Use most recent config file 'C:\Users\ADMIN\.memgpt\configs\2023-10-30_08_25_34_AM_PDT-0700.json'? No
⚙️ No settings file found, configuring MemGPT...
? Which model would you like to use? gpt-4
? Which persona would you like MemGPT to use? memgpt_starter
     The following is a blank slate starter persona, I need to expand this to develop my own personality.
     My name is MemGPT. I am kind, thoughtful, and inquisitive.
('memgpt_starter', None)
? Which user would you like to use? basic
     First name: Chad
? Would you like to preload anything into MemGPT's archival memory? Yes
? What would you like to load? A folder or file
? Please enter the folder or file (tab for autocomplete): C:\Users\ADMIN\.memgpt\saved_state
? Would you like to compute embeddings over these files to enable embeddings search? Yes
⛔️ Embeddings on a non-OpenAI endpoint are not yet supported, falling back to substring matching search.
⚙️ Saved config file to C:\Users\ADMIN\.memgpt\configs\2023-10-31_09_25_16_PM_PDT-0700.json.
Running... [exit by typing '/exit', list available commands with '/help']
Preloaded 139 chunks into archival memory.
Initializing InMemoryStateManager with agent object
InMemoryStateManager.all_messages.len = 4
InMemoryStateManager.messages.len = 4
💭 Bootup sequence complete. Persona activated. Testing messaging functionality.
Hit enter to begin (will request first MemGPT message)
[A[K
Warning: no wrapper specified for local LLM, using the default wrapper
step() failed
user_message = None
error = 'choices'
'choices'
An exception ocurred when running agent.step():
Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\main.py", line 524, in run_agent_loop
    ) = await memgpt_agent.step(user_message, first_message=False, skip_verify=no_verify)
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\agent.py", line 1013, in step
    raise e
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\agent.py", line 949, in step
    response = await get_ai_reply_async(model=self.model, message_sequence=input_message_sequence, functions=self.functions)
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\agent.py", line 159, in get_ai_reply_async
    raise e
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\agent.py", line 140, in get_ai_reply_async
    response = await acreate(
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\openai_tools.py", line 102, in wrapper
    raise e
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\openai_tools.py", line 82, in wrapper
    return await func(*args, **kwargs)
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\openai_tools.py", line 111, in acompletions_with_backoff
    return await get_chat_completion(**kwargs)
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\local_llm\chat_completion_proxy.py", line 52, in get_chat_completion
    result = get_lmstudio_completion(prompt)
  File "D:\AI\ChatBots\MemGPT_Setup\MemGPT\memgpt\local_llm\lmstudio\api.py", line 42, in get_lmstudio_completion
    result = result["choices"][0]["message"]["content"]
KeyError: 'choices'
? Retry agent.step()? (Y/n)

- - - - -
And finally I tried pip install pymemgpt and use that as a last resort which then led to this:
D:\AI\ChatBots\MemGPT_Setup>memgpt
Warning: Running legacy run command. Run `memgpt run` instead.
? Continue with legacy CLI? Yes
⚙️ Found saved config file.
? Use most recent config file 'C:\Users\ADMIN\.memgpt\configs\2023-10-31_09_25_16_PM_PDT-0700.json'? Yes
⛔️ Embeddings on a non-OpenAI endpoint are not yet supported, falling back to substring matching search.
⚙️ Saved config file to C:\Users\ADMIN\.memgpt\configs\2023-10-31_09_25_16_PM_PDT-0700.json.
Running... [exit by typing '/exit', list available commands with '/help']
Preloaded 139 chunks into archival memory.
Initializing InMemoryStateManager with agent object
InMemoryStateManager.all_messages.len = 4
InMemoryStateManager.messages.len = 4
💭 Bootup sequence complete. Persona activated. Testing messaging functionality.
Hit enter to begin (will request first MemGPT message)
[A[K
Warning: no wrapper specified for local LLM, using the default wrapper
step() failed
user_message = None
error = 'choices'
'choices'

I tried running it again and even with venv this is what I got:
D:\AI\ChatBots\MemGPT_Setup\MemGPT>memgpt run
? Do you want to enable MemGPT with Open AI? Yes
? Open AI API keys not found in enviornment - please enter: http://localhost:1234
? Do you want to enable MemGPT with Azure? No
? Select default endpoint: http://localhost:1234
? Select default preset: memgpt_chat
? Select default model (recommended: gpt-4): gpt-4
['memgpt_doc', 'memgpt_starter', 'sam', 'sam_pov', 'sam_simple_pov_gpt35']
? Select default persona: memgpt_starter
['basic', 'cs_phd']
? Select default human: basic
Saving config to C:\Users\ADMIN\.memgpt/config
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\embeddings\ │
│ huggingface.py:58 in __init__                                                                    │
│                                                                                                  │
│    55 │   │   callback_manager: Optional[CallbackManager] = None,                                │
│    56 │   ):                                                                                     │
│    57 │   │   try:                                                                               │
│ ❱  58 │   │   │   from transformers import AutoModel, AutoTokenizer                              │
│    59 │   │   except ImportError:                                                                │
│    60 │   │   │   raise ImportError(                                                             │
│    61 │   │   │   │   "HuggingFaceEmbedding requires transformers to be installed.\n"            │
│                                                                                                  │
│ ╭─────────────────── locals ───────────────────╮                                                 │
│ │      cache_folder = None                     │                                                 │
│ │  callback_manager = None                     │                                                 │
│ │            device = None                     │                                                 │
│ │  embed_batch_size = 10                       │                                                 │
│ │        max_length = None                     │                                                 │
│ │             model = None                     │                                                 │
│ │        model_name = 'BAAI/bge-small-en-v1.5' │                                                 │
│ │         normalize = True                     │                                                 │
│ │           pooling = 'cls'                    │                                                 │
│ │ query_instruction = None                     │                                                 │
│ │              self = HuggingFaceEmbedding()   │                                                 │
│ │  text_instruction = None                     │                                                 │
│ │         tokenizer = None                     │                                                 │
│ │    tokenizer_name = None                     │                                                 │
│ │ trust_remote_code = False                    │                                                 │
│ ╰──────────────────────────────────────────────╯                                                 │
│                                                                                                  │
│ C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.p │
│ y:26 in <module>                                                                                 │
│                                                                                                  │
│     23 from typing import TYPE_CHECKING                                                          │
│     24                                                                                           │
│     25 # Check the dependencies satisfy the minimal versions required.                           │
│ ❱   26 from . import dependency_versions_check                                                   │
│     27 from .utils import (                                                                      │
│     28 │   OptionalDependencyNotAvailable,                                                       │
│     29 │   _LazyModule,                                                                          │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ dependency_versions_table = <module 'transformers.dependency_versions_table' from            │ │
│ │                             'C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python310\… │ │
│ │             TYPE_CHECKING = False                                                            │ │
│ │                     utils = <module 'transformers.utils' from                                │ │
│ │                             'C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python310\… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dependency │
│ _versions_check.py:57 in <module>                                                                │
│                                                                                                  │
│   54 │   │   │   if not is_accelerate_available():                                               │
│   55 │   │   │   │   continue  # not required, check version only if installed                   │
│   56 │   │                                                                                       │
│ ❱ 57 │   │   require_version_core(deps[pkg])                                                     │
│   58 │   else:                                                                                   │
│   59 │   │   raise ValueError(f"can't find {pkg} in {deps.keys()}, check dependency_versions_    │
│   60                                                                                             │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ───────────────────────────────────────╮          │
│ │                     deps = {                                                        │          │
│ │                            │   'Pillow': 'Pillow<10.0.0',                           │          │
│ │                            │   'accelerate': 'accelerate>=0.20.3',                  │          │
│ │                            │   'av': 'av==9.2.0',                                   │          │
│ │                            │   'beautifulsoup4': 'beautifulsoup4',                  │          │
│ │                            │   'black': 'black~=23.1',                              │          │
│ │                            │   'codecarbon': 'codecarbon==1.2.0',                   │          │
│ │                            │   'cookiecutter': 'cookiecutter==1.7.3',               │          │
│ │                            │   'dataclasses': 'dataclasses',                        │          │
│ │                            │   'datasets': 'datasets!=2.5.0',                       │          │
│ │                            │   'decord': 'decord==0.6.0',                           │          │
│ │                            │   ... +76                                              │          │
│ │                            }                                                        │          │
│ │  is_accelerate_available = <function is_accelerate_available at 0x000002435C0CED40> │          │
│ │  is_tokenizers_available = <function is_tokenizers_available at 0x000002435C0CEB00> │          │
│ │                      pkg = 'accelerate'                                             │          │
│ │ pkgs_to_check_at_runtime = [                                                        │          │
│ │                            │   'python',                                            │          │
│ │                            │   'tqdm',                                              │          │
│ │                            │   'regex',                                             │          │
│ │                            │   'requests',                                          │          │
│ │                            │   'packaging',                                         │          │
│ │                            │   'filelock',                                          │          │
│ │                            │   'numpy',                                             │          │
│ │                            │   'tokenizers',                                        │          │
│ │                            │   'huggingface-hub',                                   │          │
│ │                            │   'safetensors',                                       │          │
│ │                            │   ... +2                                               │          │
│ │                            ]                                                        │          │
│ │          require_version = <function require_version at 0x000002435C115510>         │          │
│ │     require_version_core = <function require_version_core at 0x000002435C1155A0>    │          │
│ ╰─────────────────────────────────────────────────────────────────────────────────────╯          │
│                                                                                                  │
│ C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\vers │
│ ions.py:117 in require_version_core                                                              │
│                                                                                                  │
│   114 def require_version_core(requirement):                                                     │
│   115 │   """require_version wrapper which emits a core-specific hint on failure"""              │
│   116 │   hint = "Try: pip install transformers -U or pip install -e '.[dev]' if you're workin   │
│ ❱ 117 │   return require_version(requirement, hint)                                              │
│   118                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        hint = "Try: pip install transformers -U or pip install -e '.[dev]' if you're working │ │
│ │               wi"+11                                                                         │ │
│ │ requirement = 'accelerate>=0.20.3'                                                           │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\vers │
│ ions.py:111 in require_version                                                                   │
│                                                                                                  │
│   108 │   # check that the right version is installed if version number or a range was provide   │
│   109 │   if want_ver is not None:                                                               │
│   110 │   │   for op, want_ver in wanted.items():                                                │
│ ❱ 111 │   │   │   _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)               │
│   112                                                                                            │
│   113                                                                                            │
│   114 def require_version_core(requirement):                                                     │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │     got_ver = '0.18.0'                                                                       │ │
│ │        hint = "\nTry: pip install transformers -U or pip install -e '.[dev]' if you're       │ │
│ │               working w"+12                                                                  │ │
│ │       match = [('>=', '0.20.3')]                                                             │ │
│ │          op = '>='                                                                           │ │
│ │         pkg = 'accelerate'                                                                   │ │
│ │ requirement = 'accelerate>=0.20.3'                                                           │ │
│ │           w = '>=0.20.3'                                                                     │ │
│ │   want_full = '>=0.20.3'                                                                     │ │
│ │  want_range = ['>=0.20.3']                                                                   │ │
│ │    want_ver = '0.20.3'                                                                       │ │
│ │      wanted = {'>=': '0.20.3'}                                                               │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\vers │
│ ions.py:44 in _compare_versions                                                                  │
│                                                                                                  │
│    41 │   │   │   f" reinstalling {pkg}."                                                        │
│    42 │   │   )                                                                                  │
│    43 │   if not ops[op](version.parse(got_ver), version.parse(want_ver)):                       │
│ ❱  44 │   │   raise ImportError(                                                                 │
│    45 │   │   │   f"{requirement} is required for a normal functioning of this module, but fou   │
│    46 │   │   )                                                                                  │
│    47                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │     got_ver = '0.18.0'                                                                       │ │
│ │        hint = "\nTry: pip install transformers -U or pip install -e '.[dev]' if you're       │ │
│ │               working w"+12                                                                  │ │
│ │          op = '>='                                                                           │ │
│ │         pkg = 'accelerate'                                                                   │ │
│ │ requirement = 'accelerate>=0.20.3'                                                           │ │
│ │    want_ver = '0.20.3'                                                                       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: accelerate>=0.20.3 is required for a normal functioning of this module, but found accelerate==0.18.0.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\cli\cli.py:92 in │
│ run                                                                                              │
│                                                                                                  │
│    89 │   config = MemGPTConfig.load()                                                           │
│    90 │   original_stdout = sys.stdout  # unfortunate hack required to suppress confusing prin   │
│    91 │   sys.stdout = io.StringIO()                                                             │
│ ❱  92 │   embed_model = embedding_model(config)                                                  │
│    93 │   service_context = ServiceContext.from_defaults(llm=None, embed_model=embed_model, ch   │
│    94 │   set_global_service_context(service_context)                                            │
│    95 │   sys.stdout = original_stdout                                                           │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ───────────────────────────────────────╮          │
│ │           agent = None                                                              │          │
│ │     agent_files = []                                                                │          │
│ │          agents = []                                                                │          │
│ │          config = MemGPTConfig(                                                     │          │
│ │                   │   config_path='C:\\Users\\ADMIN\\.memgpt/config',               │          │
│ │                   │   anon_clientid='00000000000000000000581122a07091',             │          │
│ │                   │   preset='memgpt_chat',                                         │          │
│ │                   │   model_endpoint='http://localhost:1234',                       │          │
│ │                   │   model='gpt-4',                                                │          │
│ │                   │   openai_key='http://localhost:1234',                           │          │
│ │                   │   azure_key=None,                                               │          │
│ │                   │   azure_endpoint=None,                                          │          │
│ │                   │   azure_version=None,                                           │          │
│ │                   │   azure_deployment=None,                                        │          │
│ │                   │   azure_embedding_deployment=None,                              │          │
│ │                   │   default_persona='memgpt_starter',                             │          │
│ │                   │   default_human='basic',                                        │          │
│ │                   │   default_agent=None,                                           │          │
│ │                   │   embedding_model='openai',                                     │          │
│ │                   │   embedding_dim=768,                                            │          │
│ │                   │   embedding_chunk_size=300,                                     │          │
│ │                   │   archival_storage_type='local',                                │          │
│ │                   │   archival_storage_path=None,                                   │          │
│ │                   │   archival_storage_uri=None,                                    │          │
│ │                   │   recall_storage_type='local',                                  │          │
│ │                   │   recall_storage_path=None,                                     │          │
│ │                   │   recall_storage_uri=None,                                      │          │
│ │                   │   persistence_manager_type=None,                                │          │
│ │                   │   persistence_manager_save_file=None,                           │          │
│ │                   │   persistence_manager_uri=None                                  │          │
│ │                   )                                                                 │          │
│ │     data_source = None                                                              │          │
│ │           debug = False                                                             │          │
│ │           first = False                                                             │          │
│ │           human = None                                                              │          │
│ │           model = None                                                              │          │
│ │       no_verify = False                                                             │          │
│ │ original_stdout = <colorama.ansitowin32.StreamWrapper object at 0x0000024362A7CA90> │          │
│ │         persona = None                                                              │          │
│ │          preset = None                                                              │          │
│ │             yes = False                                                             │          │
│ ╰─────────────────────────────────────────────────────────────────────────────────────╯          │
│                                                                                                  │
│ C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\embeddings.py:32 │
│ in embedding_model                                                                               │
│                                                                                                  │
│   29 │   │   # return f"local:{model}"                                                           │
│   30 │   │                                                                                       │
│   31 │   │   # loads BAAI/bge-small-en-v1.5                                                      │
│ ❱ 32 │   │   return HuggingFaceEmbedding(model_name=model)                                       │
│   33                                                                                             │
│                                                                                                  │
│ ╭───────────────────────────────────────── locals ─────────────────────────────────────────╮     │
│ │               config = MemGPTConfig(                                                     │     │
│ │                        │   config_path='C:\\Users\\ADMIN\\.memgpt/config',               │     │
│ │                        │   anon_clientid='00000000000000000000581122a07091',             │     │
│ │                        │   preset='memgpt_chat',                                         │     │
│ │                        │   model_endpoint='http://localhost:1234',                       │     │
│ │                        │   model='gpt-4',                                                │     │
│ │                        │   openai_key='http://localhost:1234',                           │     │
│ │                        │   azure_key=None,                                               │     │
│ │                        │   azure_endpoint=None,                                          │     │
│ │                        │   azure_version=None,                                           │     │
│ │                        │   azure_deployment=None,                                        │     │
│ │                        │   azure_embedding_deployment=None,                              │     │
│ │                        │   default_persona='memgpt_starter',                             │     │
│ │                        │   default_human='basic',                                        │     │
│ │                        │   default_agent=None,                                           │     │
│ │                        │   embedding_model='openai',                                     │     │
│ │                        │   embedding_dim=768,                                            │     │
│ │                        │   embedding_chunk_size=300,                                     │     │
│ │                        │   archival_storage_type='local',                                │     │
│ │                        │   archival_storage_path=None,                                   │     │
│ │                        │   archival_storage_uri=None,                                    │     │
│ │                        │   recall_storage_type='local',                                  │     │
│ │                        │   recall_storage_path=None,                                     │     │
│ │                        │   recall_storage_uri=None,                                      │     │
│ │                        │   persistence_manager_type=None,                                │     │
│ │                        │   persistence_manager_save_file=None,                           │     │
│ │                        │   persistence_manager_uri=None                                  │     │
│ │                        )                                                                 │     │
│ │ HuggingFaceEmbedding = <class 'llama_index.embeddings.huggingface.HuggingFaceEmbedding'> │     │
│ │                model = 'BAAI/bge-small-en-v1.5'                                          │     │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────╯     │
│                                                                                                  │
│ C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\embeddings\ │
│ huggingface.py:60 in __init__                                                                    │
│                                                                                                  │
│    57 │   │   try:                                                                               │
│    58 │   │   │   from transformers import AutoModel, AutoTokenizer                              │
│    59 │   │   except ImportError:                                                                │
│ ❱  60 │   │   │   raise ImportError(                                                             │
│    61 │   │   │   │   "HuggingFaceEmbedding requires transformers to be installed.\n"            │
│    62 │   │   │   │   "Please install transformers with `pip install transformers`."             │
│    63 │   │   │   )                                                                              │
│                                                                                                  │
│ ╭─────────────────── locals ───────────────────╮                                                 │
│ │      cache_folder = None                     │                                                 │
│ │  callback_manager = None                     │                                                 │
│ │            device = None                     │                                                 │
│ │  embed_batch_size = 10                       │                                                 │
│ │        max_length = None                     │                                                 │
│ │             model = None                     │                                                 │
│ │        model_name = 'BAAI/bge-small-en-v1.5' │                                                 │
│ │         normalize = True                     │                                                 │
│ │           pooling = 'cls'                    │                                                 │
│ │ query_instruction = None                     │                                                 │
│ │              self = HuggingFaceEmbedding()   │                                                 │
│ │  text_instruction = None                     │                                                 │
│ │         tokenizer = None                     │                                                 │
│ │    tokenizer_name = None                     │                                                 │
│ │ trust_remote_code = False                    │                                                 │
│ ╰──────────────────────────────────────────────╯                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: HuggingFaceEmbedding requires transformers to be installed.
Please install transformers with `pip install transformers`.

**Comment by ProjCRys** [comment]
Tried 'memgpt run' with a new bat file here's a different error:
- - - - - 
bat file
@echo off

:: Define the paths to Python and the venv
set PYTHON_EXECUTABLE=C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\python.exe
set VENV_DIR=D:\AI\ChatBots\MemGPT_Setup\venv

:: Create the virtual environment
"%PYTHON_EXECUTABLE%" -m venv "%VENV_DIR%"

:: Check if the virtual environment creation was successful
if %errorlevel% neq 0 (
    echo An error occurred while creating the virtual environment. Press any key to exit.
    pause >nul
    exit /b %errorlevel%
)

:: Activate the virtual environment
call "%VENV_DIR%\Scripts\activate"

:: Install pymemgpt using pip
pip install pymemgpt
pip install transformers
pip install torch

:: Check if the installation was successful
if %errorlevel% neq 0 (
    echo An error occurred while installing pymemgpt. Press any key to exit.
    pause >nul
    exit /b %errorlevel%
)

set OPENAI_API_BASE=http://localhost:1234
set BACKEND_TYPE=lmstudio
cls

:: Run memgpt (replace this with your specific memgpt command)
memgpt run

:: Check if memgpt encountered an error
if %errorlevel% neq 0 (
    echo An error occurred while running memgpt. Press any key to exit.
    pause >nul
    exit /b %errorlevel%
)

:: Deactivate the virtual environment
deactivate

:: Pause to allow the user to review the output
echo Press any key to exit.
pause >nul


- - - - -
Output:
? Would you like to select an existing agent? No
Creating new agent...
Created new agent agent_5.
Hit enter to begin (will request first MemGPT message)
[A[K
Warning: no wrapper specified for local LLM, using the default wrapper
step() failed
user_message = None
error = Failed to decode JSON from LLM output:
{ {"status": "OK", "message": null, "time": "2023-11-01 06:05:36 AM PDT-0700"}}
Failed to decode JSON from LLM output:
{ {"status": "OK", "message": null, "time": "2023-11-01 06:05:36 AM PDT-0700"}}
An exception ocurred when running agent.step():
Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\local_llm\llm_chat_completion_wrappers\airoboros.py", line 392, in output_to_chat_completion_response
    function_json_output = json.loads(raw_llm_output)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\local_llm\llm_chat_completion_wrappers\airoboros.py", line 395, in output_to_chat_completion_response
    function_json_output = json.loads(raw_llm_output + "\n}")
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\main.py", line 526, in run_agent_loop
    ) = await memgpt_agent.step(user_message, first_message=False, skip_verify=no_verify)
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\agent.py", line 1084, in step
    raise e
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\agent.py", line 1020, in step
    response = await get_ai_reply_async(model=self.model, message_sequence=input_message_sequence, functions=self.functions)
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\agent.py", line 160, in get_ai_reply_async
    raise e
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\agent.py", line 141, in get_ai_reply_async
    response = await acreate(
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\openai_tools.py", line 115, in wrapper
    raise e
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\openai_tools.py", line 95, in wrapper
    return await func(*args, **kwargs)
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\openai_tools.py", line 124, in acompletions_with_backoff
    return get_chat_completion(**kwargs)
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\local_llm\chat_completion_proxy.py", line 62, in get_chat_completion
    chat_completion_result = llm_wrapper.output_to_chat_completion_response(result)
  File "D:\AI\ChatBots\MemGPT_Setup\venv\lib\site-packages\memgpt\local_llm\llm_chat_completion_wrappers\airoboros.py", line 397, in output_to_chat_completion_response
    raise Exception(f"Failed to decode JSON from LLM output:\n{raw_llm_output}")
Exception: Failed to decode JSON from LLM output:
{ {"status": "OK", "message": null, "time": "2023-11-01 06:05:36 AM PDT-0700"}}
? Retry agent.step()? (Y/n)

**Comment by ProjCRys** [comment]
Current state of issue #248
