### ISSUE TITLE
Fails to truncate prompt tokens

### ISSUE THREAD

**Issue by vampirismtrueblood** [cpacker/MemGPT#360]
**Describe the bug**
MemGPT fails to truncate prompt tokens, and crashes when prompt exceeds 8000 tokens. No code modification was made and code was last pulled today.

**To Reproduce**
1. memgpt run
2. keep chatting with it, till you exceed 8000 tokens
3. See error

**Expected behavior**
MemGPT truncates the prompt, keep all important data in a database, and continue working normally.

**How did you install MemGPT?**

- From source?
  - With `git clone git@github.com:cpacker/MemGPT.git` and `pip install -r requirements.txt`?

**Your setup (please complete the following information)**

- Your OS Linux
- Where you're trying to run MemGPT from
  - Terminal
- Your python version (run `python --version`) 3.11.4

- If you installed from source:
  - Your current git commit (run `git describe --tags`) 0.1.15-66-gf46cc3b

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- The exact model you're trying to use (link to the HuggingFace page you downloaded it from)
  - https://huggingface.co/ehartford/dolphin-2.2-mistral-7b
  
- The local LLM backend you are using (web UI? LM Studio?) web UI
- Your hardware for the local LLM backend (local computer? operating system? remote RunPod?) Local Ubuntu 22.04
- Your hardware for the MemGPT command (same computer as the local LLM backend?) yes
- The full output (or as much as possible) of where the LLM is failing
  - If you can include screenshots, even better!

**Error**
`
{'content': '{"status": "OK", "message": null, "time": "2023-11-07 08:56:35 PM '
            '"}',
 'name': 'send_message',
 'role': 'function'}
Warning: no wrapper specified for local LLM, using the default wrapper (you can remove this warning by specifying the wrapper with --model)
step() failed
user_message = None
error = Request exceeds maximum context length (8189 > 8000 tokens)
An exception ocurred when running agent.step(): 
Traceback (most recent call last):
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/agent.py", line 1060, in step
    response = await get_ai_reply_async(model=self.model, message_sequence=input_message_sequence, functions=self.functions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/agent.py", line 163, in get_ai_reply_async
    raise e
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/agent.py", line 144, in get_ai_reply_async
    response = await acreate(
               ^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 115, in wrapper
    raise e
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 95, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 124, in acompletions_with_backoff
    return get_chat_completion(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/local_llm/chat_completion_proxy.py", line 92, in get_chat_completion
    result = get_webui_completion(prompt, grammar=grammar_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/local_llm/webui/api.py", line 25, in get_webui_completion
    raise Exception(f"Request exceeds maximum context length ({prompt_tokens} > {LLM_MAX_TOKENS} tokens)")
Exception: Request exceeds maximum context length (8189 > 8000 tokens)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/main.py", line 608, in run_agent_loop
    new_messages, user_message, skip_next_user_input = await process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/main.py", line 584, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning = await memgpt_agent.step(
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/agent.py", line 1108, in step
    await self.summarize_messages_inplace()
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/agent.py", line 1174, in summarize_messages_inplace
    summary = await a_summarize_messages(self.model, message_sequence_to_summarize)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/memory.py", line 173, in a_summarize_messages
    response = await acreate(
               ^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 115, in wrapper
    raise e
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 95, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 124, in acompletions_with_backoff
    return get_chat_completion(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/local_llm/chat_completion_proxy.py", line 92, in get_chat_completion
    result = get_webui_completion(prompt, grammar=grammar_name)
                                                  ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'grammar_name' where it is not associated with a value
? Retry agent.step()? Yes
{'content': '{"status": "OK", "message": null, "time": "2023-11-07 08:56:35 PM '
            '"}',
 'name': 'send_message',
 'role': 'function'}
step() failed
user_message = None
error = Request exceeds maximum context length (8189 > 8000 tokens)
An exception ocurred when running agent.step(): 
Traceback (most recent call last):
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/agent.py", line 1060, in step
    response = await get_ai_reply_async(model=self.model, message_sequence=input_message_sequence, functions=self.functions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/agent.py", line 163, in get_ai_reply_async
    raise e
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/agent.py", line 144, in get_ai_reply_async
    response = await acreate(
               ^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 115, in wrapper
    raise e
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 95, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 124, in acompletions_with_backoff
    return get_chat_completion(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/local_llm/chat_completion_proxy.py", line 92, in get_chat_completion
    result = get_webui_completion(prompt, grammar=grammar_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/local_llm/webui/api.py", line 25, in get_webui_completion
    raise Exception(f"Request exceeds maximum context length ({prompt_tokens} > {LLM_MAX_TOKENS} tokens)")
Exception: Request exceeds maximum context length (8189 > 8000 tokens)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/main.py", line 608, in run_agent_loop
    new_messages, user_message, skip_next_user_input = await process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/main.py", line 584, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning = await memgpt_agent.step(
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/agent.py", line 1108, in step
    await self.summarize_messages_inplace()
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/agent.py", line 1174, in summarize_messages_inplace
    summary = await a_summarize_messages(self.model, message_sequence_to_summarize)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/memory.py", line 173, in a_summarize_messages
    response = await acreate(
               ^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 115, in wrapper
    raise e
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 95, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/openai_tools.py", line 124, in acompletions_with_backoff
    return get_chat_completion(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nvme_ugreen_usb/ai_agents/MemGPT/memgpt/local_llm/chat_completion_proxy.py", line 92, in get_chat_completion
    result = get_webui_completion(prompt, grammar=grammar_name)
                                                  ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'grammar_name' where it is not associated with a value`

**Comment by vampirismtrueblood** [comment]
It seems to be fixed in 0.1.15-90-g7d6aa40.

Issue no longer happens
