### ISSUE TITLE
Using local networked LLM has issues

### ISSUE THREAD

**Issue by iplayfast** [cpacker/MemGPT#392]
**Describe the bug**
On network I have a computer running text-generation_webui with openai api installed/tested/working with autogen.
set up my openai 
export OPENAI_API_KEY=NotMatter
export OPENAI_API_BASE=195.168.0.50:5000/V1
configure memgpt using the configuration script (seemed successful)
memgpt run
asks if I would like an existing agent, select Y or n
accept default, and give message "hello world"

result doesn't communicate. Also tried with "export OPENAI_API_BASE=195.168.0.50:5000"

step() failed
user_message = None
error = Error communicating with OpenAI
Error communicating with OpenAI
An exception ocurred when running agent.step(): 
Traceback (most recent call last):
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/api_requestor.py", line 678, in arequest_raw
    result = await session.request(**request_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/aiohttp/client.py", line 534, in _request
    req = self._request_class(
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 302, in __init__
    self.update_host(url)
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 361, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: 195.168.0.50:5000/V1/chat/completions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/memgpt/main.py", line 613, in run_agent_loop
    new_messages, user_message, skip_next_user_input = await process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/memgpt/main.py", line 589, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning = await memgpt_agent.step(
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/memgpt/agent.py", line 1124, in step
    raise e
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/memgpt/agent.py", line 1060, in step
    response = await get_ai_reply_async(model=self.model, message_sequence=input_message_sequence, functions=self.functions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/memgpt/agent.py", line 164, in get_ai_reply_async
    raise e
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/memgpt/agent.py", line 145, in get_ai_reply_async
    response = await acreate(
               ^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/memgpt/openai_tools.py", line 115, in wrapper
    raise e
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/memgpt/openai_tools.py", line 95, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/memgpt/openai_tools.py", line 135, in acompletions_with_backoff
    return await openai.ChatCompletion.acreate(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 219, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/api_requestor.py", line 374, in arequest
    result = await self.arequest_raw(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/api_requestor.py", line 695, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI

**Comment by cpacker** [comment]
Sorry for the delay - if you are having issues, please see the updated documentation for AutoGen (https://memgpt.readthedocs.io/en/latest/autogen/) and local/open LLMs (https://memgpt.readthedocs.io/en/latest/webui/).
