### ISSUE TITLE
Using local LLM OPEN_AI_KEY is not working

### ISSUE THREAD

**Issue by izevar** [cpacker/MemGPT#424]
Using a local LLM is the env var OPENAI_API_KEY megpt ask you to unset it, if is unset do give an error of missing OPENAI_API_KEY env.

(memgpt) xxxxx@xxxx MemGPT % unset OPENAI_API_KEY       
(memgpt) xxxxx@xxxx MemGPT % python3 ./main.py run --agent agent_1 --model airoboros-l2-70b-2.1
Using existing agent agent_1
Hit enter to begin (will request first MemGPT message)

An exception ocurred when running agent.step(): 
Traceback (most recent call last):
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/main.py", line 608, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/main.py", line 584, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning = memgpt_agent.step(
                                                                      ^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 657, in step
    raise e
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 583, in step
    response = get_ai_reply(
               ^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 130, in get_ai_reply
    raise e
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 110, in get_ai_reply
    response = create(
               ^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/openai_tools.py", line 53, in wrapper
    raise e
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/openai_tools.py", line 34, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/openai_tools.py", line 75, in completions_with_backoff
    return openai.ChatCompletion.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
? Retry agent.step()? (Y/n)                                                                                                                             

Cancelled by user

> Enter your message:                                                                                                                                   

Cancelled by user

Finished.
(memgpt) xxxxx@xxxx MemGPT % export OPENAI_API_KEY="none"                                  
(memgpt) xxxxx@xxxx MemGPT % python3 ./main.py run --agent agent_1 --model airoboros-l2-70b-2.1
Using existing agent agent_1
Hit enter to begin (will request first MemGPT message)

An exception ocurred when running agent.step(): 
Traceback (most recent call last):
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/main.py", line 608, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/main.py", line 584, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning = memgpt_agent.step(
                                                                      ^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 657, in step
    raise e
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 583, in step
    response = get_ai_reply(
               ^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 130, in get_ai_reply
    raise e
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 110, in get_ai_reply
    response = create(
               ^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/openai_tools.py", line 53, in wrapper
    raise e
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/openai_tools.py", line 34, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/openai_tools.py", line 75, in completions_with_backoff
    return openai.ChatCompletion.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: none. You can find your API key at https://platform.openai.com/account/api-keys.
? Retry agent.step()? Yes
An exception ocurred when running agent.step(): 
Traceback (most recent call last):
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/main.py", line 608, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/main.py", line 584, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning = memgpt_agent.step(
                                                                      ^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 657, in step
    raise e
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 583, in step
    response = get_ai_reply(
               ^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 130, in get_ai_reply
    raise e
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/agent.py", line 110, in get_ai_reply
    response = create(
               ^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/openai_tools.py", line 53, in wrapper
    raise e
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/openai_tools.py", line 34, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/Documents/AIProjects/MemGPT/memgpt/openai_tools.py", line 75, in completions_with_backoff
    return openai.ChatCompletion.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/Users/XXX/anaconda3/envs/memgpt/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: none. You can find your API key at https://platform.openai.com/account/api-keys.
? Retry agent.step()? (Y/n)                                                                                                                             

Cancelled by user

> Enter your message:                                                                                                                                   

Cancelled by user

Finished.

for reference the config file is the following
[defaults]
model = local
preset = memgpt_chat
model_endpoint = http://localhost:8080
persona = orii
human = Antonio

[openai]
key = none

[embedding]
model = local
dim = 384
chunk_size = 300

[archival_storage]
type = local

[client]
anon_clientid = 00000000000000000000XaXXXXXXXXXX

**Comment by cpacker** [comment]
Should be fixed by #432 - let us know if things are still not working (once we push the pypi update)
