### ISSUE TITLE
With ollama, run into error """not supported between instances of 'int' and 'str'"""

### ISSUE THREAD

**Issue by lojian** [cpacker/MemGPT#442]
**Describe the bug**
When running "memgpt run" with a local LLM: OLLAMA, it does not work

**To Reproduce**

`
ccde1gl1068:~/code> memgpt configure
? Do you want to enable MemGPT with OpenAI? No
? Do you want to enable MemGPT with Azure? No
? Select default inference endpoint: http://localhost:11434
? Select default embedding endpoint: local
? Select default preset: memgpt_chat
? Select your model's context window (for Mistral 7B models, this is probably 8k / 8192): 8192
? Select default persona: memgpt_starter
? Select default human: cs_phd
? Select storage backend for archival data: local
Saving config to /data/i063123/.memgpt/config

i063123@ccde1gl1068:~/code> memgpt run
? Would you like to select an existing agent? No
Creating new agent...
Created new agent agent_2.
Hit enter to begin (will request first MemGPT message)

Warning: no wrapper specified for local LLM, using the default wrapper (you can remove this warning by specifying the wrapper with --model)
An exception ocurred when running agent.step():
Traceback (most recent call last):
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/main.py", line 608, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/main.py", line 584, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning = memgpt_agent.step(
                                                                      ^^^^^^^^^^^^^^^^^^
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/agent.py", line 657, in step
    raise e
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/agent.py", line 583, in step
    response = get_ai_reply(
               ^^^^^^^^^^^^^
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/agent.py", line 130, in get_ai_reply
    raise e
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/agent.py", line 110, in get_ai_reply
    response = create(
               ^^^^^^^
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/openai_tools.py", line 53, in wrapper
    raise e
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/openai_tools.py", line 34, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/openai_tools.py", line 62, in completions_with_backoff
    return get_chat_completion(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/local_llm/chat_completion_proxy.py", line 103, in get_chat_completion
    result = get_ollama_completion(prompt, context_window)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/i063123/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/memgpt/local_llm/ollama/api.py", line 19, in get_ollama_completion
    if prompt_tokens > context_window:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'int' and 'str'
`
**Expected behavior**

**Screenshots**

**Additional context**

---

**How did you install MemGPT?**

- From the official package? `pip install pymemgpt`
- From source?
  - With [poetry](https://github.com/cpacker/MemGPT#development)?
  - With `git clone git@github.com:cpacker/MemGPT.git` and `pip install -r requirements.txt`?

**Your setup (please complete the following information)**

- Your OS (Linux, MacOS, Windows)
- Where you're trying to run MemGPT from
  - Terminal? PowerShell? cmd.exe?
- Your python version (run `python --version`)
-  If you installed with `pip install pymemgpt`:
  - `pymemgpt` version (run `pip list | grep pymemgpt`)
- If you installed from source:
  - Your current git commit (run `git describe --tags`)
``
**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- The exact model you're trying to use (link to the HuggingFace page you downloaded it from)
  - We need the EXACT model name, including quantization scheme, e.g.: `dolphin-2.1-mistral-7b.Q6_K.gguf` (not just `dolphin-2.1-mistral`)
- The local LLM backend you are using (web UI? LM Studio?)
- Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)
- Your hardware for the MemGPT command (same computer as the local LLM backend?)
- The full output (or as much as possible) of where the LLM is failing
  - If you can include screenshots, even better!

**Comment by sarahwooders** [comment]
This should be fixed in version 0.2.3, so closing this issue - but please let us know if there are other problems.
