### ISSUE TITLE
Bug with fix

### ISSUE THREAD

**Issue by alexandj90** [cpacker/MemGPT#443]
I get this after memgpt run and press enter to activate chat session:

"self.config.context_window" is not an integer as expected, in the agent.py file, printing this to terminal:

```
💭 Let's make sure everything is running smoothly and get ready for what's to come.
🤖 Hey! Welcome to your first session with me. What coding problem can we tackle today?
An exception ocurred when running agent.step():
Traceback (most recent call last):
  File "C:\User\User\anaconda3\Lib\site-packages\memgpt\main.py", line 608, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\memgpt\main.py", line 584, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning = memgpt_agent.step(
                                                                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\memgpt\agent.py", line 657, in step
    raise e
  File "C:\Users\User\anaconda3\Lib\site-packages\memgpt\agent.py", line 631, in step
    if current_total_tokens > MESSAGE_SUMMARY_WARNING_FRAC * self.config.context_window:
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can't multiply sequence by non-int of type 'float'
? Retry agent.step()? (Y/n)
```

It's being treated as a sequence type instead of an integer.

This fixed it for me:

_context_window=self.config.context_window_

**set to**

context_window=int(self.config.context_window)

...throughout the agent.py file.

**How did you install MemGPT?**

- From source
  - With [poetry](https://github.com/cpacker/MemGPT#development)?

**Comment by deej81** [comment]
I think this is fixed by https://github.com/cpacker/MemGPT/pull/444 - suggest closing
