### ISSUE TITLE
Is there an easy to use Memgpt API? 

### ISSUE THREAD

**Issue by ProjCRys** [cpacker/MemGPT#480]
**Is your feature request related to a problem? Please describe.**

I wanted to integrate memgpt to my project. However, this projects is a bit too complicated for me. 

**Describe the solution you'd like**

Maybe having an api folder with each python standalone file using memgpts functions like:
- Simple output generation
- Using how to use agents
- Chat with designated archive memory folder
- Streaming output generation
- Using LlaVa on sending images
- Others...  

**Describe alternatives you've considered**

I could use memgpt as is using my terminal emulator code  (basically a python file I could use when I want to run things on different programming languages), however the CLI of memgpt messes up the terminal reading in cases like they are:

::Thinking... 
>> choosing options
And key press detection (Choosing y/n) 

**Additional context**

**Comment by CUexter** [comment]
There is a websocket server

**Comment by BabellDev** [comment]
Not sure if this is what you're looking for, but I've recently posted some code I have been experimenting with here:
https://github.com/cpacker/MemGPT/discussions/315

**Comment by ProjCRys** [comment]
> Not sure if this is what you're looking for, but I've recently posted some code I have been experimenting with here: #315

I tried running it as a standalone file. Here's what I did.

pip install pymemgpt

Here's the code I use so I can run the LLM using LM Studio server inference:
import os

import memgpt.constants as constants
import memgpt.presets.presets as presets
import openai

from pathlib import Path
from memgpt.agent import Agent
from memgpt.config import AgentConfig
from memgpt.humans import humans
from memgpt.interface import CLIInterface as interface
from memgpt.persistence_manager import LocalStateManager
from memgpt.personas import personas

# Set your OpenAI API key
os.environ['OPENAI_API_KEY'] = 'TODO'
os.environ['BACKEND_TYPE'] = 'lmstudio'

# Point to your config file (or remove this line if you just want to use the default)
os.environ['MEMGPT_CONFIG_PATH'] = Path.home().joinpath('.memgpt').joinpath('config').as_posix()

# Necessary to avoid errors when LLM is invoked
openai.api_key = os.getenv('OPENAI_API_KEY')
openai.api_base = 'http://localhost:1234/v1'

agent_config = AgentConfig(
    name="Nana",
    persona=personas.DEFAULT,
    human=humans.DEFAULT,
    model=constants.DEFAULT_MEMGPT_MODEL,
    preset=presets.DEFAULT_PRESET,
    model_endpoint_type="lmstudio",
    model_endpoint="http://localhost:1234/v1",
)

NEW_AGENT = False
if NEW_AGENT:
    persistence_manager = LocalStateManager(agent_config)

    memgpt_agent = presets.use_preset(
        preset_name=presets.DEFAULT_PRESET,
        agent_config=agent_config,
        model=constants.DEFAULT_MEMGPT_MODEL,
        persona=personas.DEFAULT,
        human=humans.DEFAULT,
        interface=interface,
        persistence_manager=persistence_manager,
    )

    memgpt_agent.step(user_message="Hi my name is Bill Gates.  I love the Windows OS!", first_message=True, skip_verify=False)
    memgpt_agent.step(user_message="I am 68 years old, born October 28, 1955", first_message=False, skip_verify=False)
    memgpt_agent.save()
else:
    memgpt_agent = Agent.load_agent(interface, agent_config)
    memgpt_agent.step(user_message="What is my name?", first_message=False, skip_verify=False)
    memgpt_agent.step(user_message="What is my age?", first_message=False, skip_verify=False)

**Comment by ProjCRys** [comment]
> I'm sorry to hear you are having trouble with the example @ProjCRys.
> 
> I've verified that the module exists in the latest code base: https://github.com/cpacker/MemGPT/blob/0ee2b8c01019d0355741054ef6ba909fbc5fdb52/memgpt/presets/presets.py
> 
> The same import is used in the official `memgpt_autogen.py` source:
> 
> https://github.com/cpacker/MemGPT/blob/0ee2b8c01019d0355741054ef6ba909fbc5fdb52/memgpt/autogen/memgpt_agent.py#L10
> 
> I've been running the code in a Jupyter notebook, which could make things a bit different than the command-line when it comes to packages. Could you try running your code with the `-m` switch (`D:\AI\ChatBots\MemGPT_Setup>python -m memgpt-api.py`)? Failing that, there may be something wrong in your local environment.

Ok I managed to fix the presets problem, because I'm dumb and forgot my pymemgpt is outdated. However I got this new error:

- - - - -

D:\AI\ChatBots\MemGPT_Setup>python memgpt-api.py
LLM is explicitly disabled. Using MockLLM.
Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\memgpt-api.py", line 49, in <module>
    memgpt_agent.step(user_message="Hi my name is Bill Gates.  I love the Windows OS!", first_message=True, skip_verify=False)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 655, in step
    raise e
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 575, in step
    response = self.get_ai_reply(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 803, in get_ai_reply
    raise e
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 785, in get_ai_reply
    response = chat_completion_with_backoff(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 57, in wrapper
    raise e
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 92, in chat_completion_with_backoff
    return openai.ChatCompletion.create(**kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 428, in handle_error_response
    error_code=error_data.get("code"),
AttributeError: 'str' object has no attribute 'get'

D:\AI\ChatBots\MemGPT_Setup>python memgpt-api.py
/load error: no .json checkpoint files found
Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\memgpt-api.py", line 53, in <module>
    memgpt_agent = Agent.load_agent(interface, agent_config)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 283, in load_agent
    raise ValueError(f"Cannot load {agent_name} - no saved checkpoints found in {directory}")
ValueError: Cannot load BillsFriend - no saved checkpoints found in C:\Users\ADMIN\.memgpt\agents\BillsFriend\agent_state

- - - - -

Here's the code I used:
import os

import memgpt.constants as constants
import memgpt.presets.presets as presets
import openai

from pathlib import Path
from memgpt.agent import Agent
from memgpt.config import AgentConfig
from memgpt.humans import humans
from memgpt.interface import CLIInterface as interface
from memgpt.persistence_manager import LocalStateManager
from memgpt.personas import personas

# Set your OpenAI API key
os.environ['OPENAI_API_KEY'] = 'TODO'

# Point to your config file (or remove this line if you just want to use the default)
os.environ['MEMGPT_CONFIG_PATH'] = Path.home().joinpath('.memgpt').joinpath('openai_config').as_posix()

# Necessary to avoid errors when LLM is invoked
openai.api_key = os.getenv('OPENAI_API_KEY')
openai.api_base = 'http://localhost:1234/v1'

agent_config = AgentConfig(
    name="BillsFriend",
    persona=personas.DEFAULT,
    human=humans.DEFAULT,
    model=constants.DEFAULT_MEMGPT_MODEL,
    preset=presets.DEFAULT_PRESET,
    model_endpoint_type="openai",
    model_endpoint="http://localhost:1234/v1",
)

NEW_AGENT = False
if NEW_AGENT:
    persistence_manager = LocalStateManager(agent_config)

    memgpt_agent = presets.use_preset(
        preset_name=presets.DEFAULT_PRESET,
        agent_config=agent_config,
        model=constants.DEFAULT_MEMGPT_MODEL,
        persona=personas.DEFAULT,
        human=humans.DEFAULT,
        interface=interface,
        persistence_manager=persistence_manager,
    )

    memgpt_agent.step(user_message="Hi my name is Bill Gates.  I love the Windows OS!", first_message=True, skip_verify=False)
    memgpt_agent.step(user_message="I am 68 years old, born October 28, 1955", first_message=False, skip_verify=False)
    memgpt_agent.save()
else:
    memgpt_agent = Agent.load_agent(interface, agent_config)
    memgpt_agent.step(user_message="What is my name?", first_message=False, skip_verify=False)
    memgpt_agent.step(user_message="What is my age?", first_message=False, skip_verify=False)
    


![image](https://github.com/cpacker/MemGPT/assets/127005727/aa92b903-5542-49e4-a37d-761cd8997e5a)

config of the agent:
{
    "name": "BillsFriend",
    "persona": "sam_pov",
    "human": "cs_phd",
    "preset": "memgpt_chat",
    "context_window": 8192,
    "model": "gpt-4",
    "model_endpoint_type": "openai",
    "model_endpoint": "http://localhost:1234/v1",
    "model_wrapper": null,
    "embedding_endpoint_type": "openai",
    "embedding_endpoint": null,
    "embedding_dim": 1536,
    "embedding_chunk_size": 300,
    "data_sources": [],
    "create_time": "2023-11-22 07:58:52 AM ",
    "memgpt_version": "0.2.3",
    "agent_config_path": "C:\\Users\\ADMIN\\.memgpt\\agents\\BillsFriend\\config.json"
}

**Comment by BabellDev** [comment]
@ProjCRys did you remember to set `NEW_AGENT = True` the first time you run the code?  It's a very rough example,  you need to create a new agent the first time (which will also save),  and then you set it to `False` next time and it will load the saved agent.  I suspect you set to `False` without first creating/saving the new agent.

**Comment by ProjCRys** [comment]
> @ProjCRys did you remember to set `NEW_AGENT = True` the first time you run the code? It's a very rough example, you need to create a new agent the first time (which will also save), and then you set it to `False` next time and it will load the saved agent. I suspect you set to `False` without first creating/saving the new agent.
> 
> Edit: on second glance, I guess it would be strange to have an agent config if you _hadn't_ run with `NEW_AGENT = True`. Was there any indication that `memgpt_agent.save()` failed? Try deleting your agent folder and starting again with `True` and then `False`.

I did set it true after running it and also set it to false. I get the same result either way. Also I did what you said on deleting the agent folder, still the same result.

**Comment by BabellDev** [comment]
Ah ok, i didn't notice there were two error traces in your previous reply (I'm reading this on my phone).  If the first run with `NEW_AGENT = True` didn't pass,  then the second run with `False` definitely won't, so we'll focus on that first error which is coming from the openai call. 

I've never used LM Studio, so that's a bit of an unknown for me.  As an experiment,  would it be possible to take it out of the picture and try hitting the openai API directly (GPT-4)?  

Something else to look at:  you mentioned there was a problem with your `pymemgpt` package, maybe your `openai` package version is out of sync with MemGPT?  I found that MemGPT doesn't work with the latest version of `openai` (since the recent API changes they made).  I can let you know the exact versions I'm using when I'm back in the office tomorrow.

**Comment by ProjCRys** [comment]
> Ah ok, i didn't notice there were two error traces in your previous reply (I'm reading this on my phone). If the first run with `NEW_AGENT = True` didn't pass, then the second run with `False` definitely won't, so we'll focus on that first error which is coming from the openai call.
> 
> I've never used LM Studio, so that's a bit of an unknown for me. As an experiment, would it be possible to take it out of the picture and try hitting the openai API directly (GPT-4)?
> 
> Something else to look at: you mentioned there was a problem with your `pymemgpt` package, maybe your `openai` package version is out of sync with MemGPT? I found that MemGPT doesn't work with the latest version of `openai` (since the recent API changes they made). I can let you know the exact versions I'm using when I'm back in the office tomorrow.

Okay, I tried updating openai package and this is what i get:
D:\AI\ChatBots\MemGPT_Setup>python memgpt-api.py
Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\memgpt-api.py", line 5, in <module>
    import openai
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\__init__.py", line 8, in <module>
    from . import types
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\types\__init__.py", line 5, in <module>
    from .edit import Edit as Edit
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\types\edit.py", line 6, in <module>
    from .._models import BaseModel
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_models.py", line 22, in <module>
    from ._types import (
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_types.py", line 32, in <module>
    from httpx import URL, Proxy, Timeout, Response, BaseTransport, AsyncBaseTransport
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\__init__.py", line 48, in <module>
    from ._main import main
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_main.py", line 111, in <module>
    def format_request_headers(request: httpcore.Request, http2: bool = False) -> str:
AttributeError: module 'httpcore' has no attribute 'Request'

**Comment by BabellDev** [comment]
When running the example, I am using `pymemgpt 0.2.3` and `openai 0.28.1`.  That is a rather old version of `openai`, but that is the precise dependency installed with `pymemgpt`.  Please try these versions, and keep the code as close as possible to the original example (no LM Studio for now, just provide a valid openai API key in the spot indicated).  

A friendly tip:  you can surround code with triple-backtick characters (```) and it will nicely format it.  I see you are having trouble with pasting code in your previous replies.

**Comment by BabellDev** [comment]
See the recent edits I made to my previous comment re:  totally new project and no LM Studio.

**Comment by ProjCRys** [comment]
> See the recent edits I made to my previous comment re: totally new project and no LM Studio.

Yeah, I'll try to figure things out.

**Comment by BabellDev** [comment]
> > See the recent edits I made to my previous comment re: totally new project and no LM Studio.
> 
> Yeah, I'll try to figure things out.

It's possible there's a bug in MemGPT + LM Studio, which would be a separate issue to explore.  See if you can get it working without it for now, then you can try LM Studio again and see if it is indeed broken.  If so, it sounds like you have a good idea of what the fix might be.

**Comment by ProjCRys** [comment]
> > > See the recent edits I made to my previous comment re: totally new project and no LM Studio.
> > 
> > 
> > Yeah, I'll try to figure things out.
> 
> It's possible there's a bug in MemGPT + LM Studio, which would be a separate issue to explore. See if you can get it working without it for now, then you can try LM Studio again and see if it is indeed broken. If so, it sounds like you have a good idea of what the fix might be.

I think I found the problem? The reason it doesn't work might be because it's sending a POST request meant for OpenAI, and with LM Studio only needing these to work...
```
completion = openai.ChatCompletion.create(
  model="local-model", # this field is currently unused
  messages=[
    {"role": "system", "content": "Always answer in rhymes."},
    {"role": "user", "content": "Introduce yourself."}
  ]
)
```
... I might need to refractor the code so that it would use LM Studio's format to send the api request

**Comment by BabellDev** [comment]
If your fix works, you may consider PR back into this project.  I'm sure the community would appreciate it.

**Comment by BabellDev** [comment]
Did you set the backend provider to "local" per [these instructions](https://memgpt.readthedocs.io/en/latest/lmstudio/)?  I think you may need to change the AgentConfig like so:

```
agent_config = AgentConfig(
name="BillsFriend",
persona=personas.DEFAULT,
human=humans.DEFAULT,
model=constants.DEFAULT_MEMGPT_MODEL,
preset=presets.DEFAULT_PRESET,
model_endpoint_type="local",  # *** Using LM Studio ***
model_endpoint="http://localhost:1234/v1",
)
```

**Comment by ProjCRys** [comment]
> Did you set the backend provider to "local" per [these instructions](https://memgpt.readthedocs.io/en/latest/lmstudio/)? I think you may need to change the AgentConfig like so:
> 
> ```
> agent_config = AgentConfig(
> name="BillsFriend",
> persona=personas.DEFAULT,
> human=humans.DEFAULT,
> model=constants.DEFAULT_MEMGPT_MODEL,
> preset=presets.DEFAULT_PRESET,
> model_endpoint_type="local",  # *** Using LM Studio ***
> model_endpoint="http://localhost:1234/v1",
> )
> ```
> 
> (or maybe it needs to be "lmstudio"?)

There is progress. It changed into a familiar error but I don't know how this was fixed
- - - - -
D:\AI\ChatBots\MemGPT_Setup>python memgpt-api.py
LLM is explicitly disabled. Using MockLLM.
LLM is explicitly disabled. Using MockLLM.
Warning: no wrapper specified for local LLM, using the default wrapper (you can remove this warning by specifying the wrapper with --wrapper)
Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\memgpt-api.py", line 54, in <module>
    memgpt_agent.step(user_message="What is my name?", first_message=False, skip_verify=False)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 655, in step
    raise e
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 575, in step
    response = self.get_ai_reply(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 803, in get_ai_reply
    raise e
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 785, in get_ai_reply
    response = chat_completion_with_backoff(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 57, in wrapper
    raise e
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 111, in chat_completion_with_backoff
    return get_chat_completion(**kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\local_llm\chat_completion_proxy.py", line 88, in get_chat_completion
    result = get_lmstudio_completion(endpoint, prompt, context_window)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\local_llm\lmstudio\api.py", line 45, in get_lmstudio_completion
    result = result["choices"][0]["message"]["content"]
KeyError: 'choices'

**Comment by BabellDev** [comment]
It seems like there may be something out of sync between what LM Studio expects from an openai request/response.  OpenAI recently made some big updates to the API which is breaking a lot of projects that haven't updated.  If LM Studio is using the latest, then there will be inconsistency between it and memgpt.  

Did you get a chance to try without LM Studio yet?  I'm curious if the example code at least works in that scenario.

**Comment by BabellDev** [comment]
Regarding the OpenAI changes:
https://stackoverflow.com/questions/77435356/openai-api-new-version-v1-of-the-openai-python-package-appears-to-contain-bre

It has been a headache to get certain projects working together now.  For example:  the latest version of autogen no longer works with memgpt, because autogen has updated to use the new openai package, whereas memgpt is still on v0.28.

**Comment by ProjCRys** [comment]
> It seems like there may be something out of sync between what LM Studio expects from an openai request/response. OpenAI recently made some big updates to the API which is breaking a lot of projects that haven't updated. If LM Studio is using the latest, then there will be inconsistency between it and memgpt.
> 
> Did you get a chance to try without LM Studio yet? I'm curious if the example code at least works in that scenario (would need to undo the change to `AgentConfig` first).

Tried using my openai key, how do you change model to gpt3?
D:\AI\ChatBots\MemGPT_Setup>python memgpt-api.py
LLM is explicitly disabled. Using MockLLM.
Traceback (most recent call last):
  File "D:\AI\ChatBots\MemGPT_Setup\memgpt-api.py", line 49, in <module>
    memgpt_agent.step(user_message="Hi my name is Bill Gates.  I love the Windows OS!", first_message=True, skip_verify=False)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 655, in step
    raise e
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 575, in step
    response = self.get_ai_reply(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 803, in get_ai_reply
    raise e
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 785, in get_ai_reply
    response = chat_completion_with_backoff(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 57, in wrapper
    raise e
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 92, in chat_completion_with_backoff
    return openai.ChatCompletion.create(**kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

**Comment by ProjCRys** [comment]
> > It seems like there may be something out of sync between what LM Studio expects from an openai request/response. OpenAI recently made some big updates to the API which is breaking a lot of projects that haven't updated. If LM Studio is using the latest, then there will be inconsistency between it and memgpt.
> > Did you get a chance to try without LM Studio yet? I'm curious if the example code at least works in that scenario (would need to undo the change to `AgentConfig` first).
> 
> Tried using my openai key, how do you change model to gpt3?
> 
> D:\AI\ChatBots\MemGPT_Setup>python memgpt-api.py LLM is explicitly disabled. Using MockLLM. Traceback (most recent call last): File "D:\AI\ChatBots\MemGPT_Setup\memgpt-api.py", line 49, in memgpt_agent.step(user_message="Hi my name is Bill Gates. I love the Windows OS!", first_message=True, skip_verify=False) File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 655, in step raise e File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 575, in step response = self.get_ai_reply( File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 803, in get_ai_reply raise e File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\agent.py", line 785, in get_ai_reply response = chat_completion_with_backoff( File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 57, in wrapper raise e File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 38, in wrapper return func(*args, **kwargs) File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\memgpt\openai_tools.py", line 92, in chat_completion_with_backoff return openai.ChatCompletion.create(**kwargs) File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create return super().create(*args, **kwargs) File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create response, _, api_key = requestor.request( File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 299, in request resp, got_stream = self._interpret_response(result, stream) File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response self._interpret_response_line( File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line raise self.handle_error_response( openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

## Okay, I tried gpt3.5 turbo it got stuck here:
D:\AI\ChatBots\MemGPT_Setup>python memgpt-api.py
LLM is explicitly disabled. Using MockLLM.

**Comment by BabellDev** [comment]
This is my first time trying with with GPT-3.5 and likewise not having much success.  However, when I configure the CLI to use GPT-3.5 (gpt-3.5-turbo-16k) then it _does_ seem to work.  I'm trying to debug that a bit and see what's different from my code.

**Comment by BabellDev** [comment]
I got it working.  The main thing was to set those `skip_verify` arguments to `True`.  I'm not sure what the implications are, but at least it works. 

Here is the updated code:
```
import os

import memgpt.constants as constants
import memgpt.presets.presets as presets
import openai

from pathlib import Path
from memgpt.agent import Agent
from memgpt.config import AgentConfig
from memgpt.humans import humans
from memgpt.interface import CLIInterface as interface
from memgpt.persistence_manager import LocalStateManager
from memgpt.personas import personas

# Set your OpenAI API key
os.environ['OPENAI_API_KEY'] = 'TODO'

# Point to your config file (or remove this line if you just want to use the default)
os.environ['MEMGPT_CONFIG_PATH'] = Path.home().joinpath('.memgpt').joinpath('config').as_posix()

# Necessary to avoid errors when LLM is invoked
openai.api_key = os.getenv('OPENAI_API_KEY')
openai.api_base = 'https://api.openai.com/v1'

agent_config = AgentConfig(
    name="BillsNewestFriend",
    persona=personas.DEFAULT,
    human=humans.DEFAULT,
    model="gpt-3.5-turbo-16k",
    preset=presets.DEFAULT_PRESET,
    model_endpoint_type="openai",
    model_endpoint="https://api.openai.com/v1",
)

NEW_AGENT = True
if NEW_AGENT:
    persistence_manager = LocalStateManager(agent_config)

    memgpt_agent = presets.use_preset(
        preset_name=presets.DEFAULT_PRESET,
        agent_config=agent_config,
        model="gpt-3.5-turbo-16k",
        persona=personas.DEFAULT,
        human=humans.DEFAULT,
        interface=interface,
        persistence_manager=persistence_manager,
    )

    memgpt_agent.step(user_message="Hi my name is Bill Gates.  I love the Windows OS!", first_message=True, skip_verify=True)
    memgpt_agent.step(user_message="I am 68 years old, born October 28, 1955", first_message=False, skip_verify=True)
    memgpt_agent.save()
else:
    memgpt_agent = Agent.load_agent(interface, agent_config)
    memgpt_agent.step(user_message="What is my name?", first_message=False, skip_verify=True)
    memgpt_agent.step(user_message="What is my age?", first_message=False, skip_verify=True)
```

This is the config file I'm using:
```
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = gpt-3.5-turbo-16k
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 16385

[openai]
key = TODO

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = local

[version]
memgpt_version = 0.2.3

[client]
anon_clientid = 0000000000000000000028dfebe08e49
```

This code is expecting to find the above in a file named simply `config` in your user .memgpt directory.  Update the API key accordingly.

**Comment by ProjCRys** [comment]
> [defaults]
> preset = memgpt_chat
> persona = sam_pov
> human = basic
> 
> [model]
> model = gpt-3.5-turbo-16k
> model_endpoint = https://api.openai.com/v1
> model_endpoint_type = openai
> context_window = 16385
> 
> [openai]
> key = TODO
> 
> [embedding]
> embedding_endpoint_type = openai
> embedding_endpoint = https://api.openai.com/v1
> embedding_dim = 1536
> embedding_chunk_size = 300
> 
> [archival_storage]
> type = local
> 
> [version]
> memgpt_version = 0.2.3
> 
> [client]
> anon_clientid = 0000000000000000000028dfebe08e49

Tried doing this I get the same error:
D:\AI\ChatBots\MemGPT_Setup>python memgpt-api.py
LLM is explicitly disabled. Using MockLLM.



I don't know if this had to this with it XD
![image](https://github.com/cpacker/MemGPT/assets/127005727/9479c0d8-1cf2-4ecf-8252-4826333e6be8)

**Comment by BabellDev** [comment]
You can safely ignore that message `LLM is explicitly disabled. Using MockLLM`, here is my working output despite that message:
![image](https://github.com/cpacker/MemGPT/assets/67427742/aec6aed5-f6cc-49af-ac25-907d54781008)

It is also mentioned in the [official docs](https://memgpt.readthedocs.io/en/latest/example_data/):
![image](https://github.com/cpacker/MemGPT/assets/67427742/cdac8f0d-39b8-4d5c-8bef-c02258f3948a)

I believe that message is coming from the state manager code, and isn't referring to the LLM that is actually used for messages/reasoning.  

So with that said, once you top up your OpenAI account it should work for you. :)

**Comment by ProjCRys** [comment]
> You can safely ignore that message `LLM is explicitly disabled. Using MockLLM`, here is my working output despite that message: ![image](https://user-images.githubusercontent.com/67427742/285235623-aec6aed5-f6cc-49af-ac25-907d54781008.png)
> 
> It is also mentioned in the [official docs](https://memgpt.readthedocs.io/en/latest/example_data/): ![image](https://user-images.githubusercontent.com/67427742/285236075-cdac8f0d-39b8-4d5c-8bef-c02258f3948a.png)
> 
> That warning is related to the `LocalStateManager`, and isn't referring to the LLM that is actually used for messages/reasoning. It is ultimately coming from `llama_index\llms\utils.py (line 50)`. LlamaIndex is a dependency of MemGPT, and I guess for whatever reason the code takes a path that results in this warning being issued.
> 
> So with that said, once you top up your OpenAI account it should work for you. :)
> 
> EDIT: I was curious why that warning doesn't show up when using the MemGPT CLI, and I found this: ![image](https://user-images.githubusercontent.com/67427742/285247783-40df6dd5-07bc-4ceb-ac2f-fd76b78999c8.png)
> 
> Therefore it _is_ being printed, but the output is suppressed.

For me it always get stuck on the error and not generating any output even if I want for a few hours.

**Comment by CUexter** [comment]
how about attach ?
Is there a way to use an API to attach data ?

**Comment by BabellDev** [comment]
> how about attach ? Is there a way to use an API to attach data ?

I haven't tried it, but the implementation of `/attach` doesn't look difficult to replicate:
https://github.com/cpacker/MemGPT/blob/c35e8720739c9b1188e9f4044516a2d5af3a1fb8/memgpt/main.py#L453C18-L453C18
