### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character

### ISSUE THREAD

**Issue by scottiesan** [cpacker/MemGPT#505]
**Describe the bug**
> Enter your message: how are you
An exception ocurred when running agent.step(): 
Traceback (most recent call last):
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/main.py", line 608, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/main.py", line 584, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning = memgpt_agent.step(
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/agent.py", line 655, in step
    raise e
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/agent.py", line 575, in step
    response = self.get_ai_reply(
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/agent.py", line 801, in get_ai_reply
    raise e
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/agent.py", line 783, in get_ai_reply
    response = chat_completion_with_backoff(
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/openai_tools.py", line 57, in wrapper
    raise e
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/openai_tools.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/memgpt/openai_tools.py", line 97, in chat_completion_with_backoff
    return openai.ChatCompletion.create(**kwargs)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/openai/api_requestor.py", line 289, in request
    result = self.request_raw(
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/openai/api_requestor.py", line 606, in request_raw
    result = _thread_context.session.request(
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/http/client.py", line 1326, in _send_request
    self.putheader(hdr, value)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/Users/scott/miniconda3/envs/memgpt/lib/python3.9/http/client.py", line 1258, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 7: ordinal not in range(256)
? Retry agent.step()? (Y/n)

**Comment by sarahwooders** [comment]
Can you share more information, e.g. what command you ran to get this error?

**Comment by scottiesan** [comment]
this was cause by openai key not set properly.  i will close it.  thank you @sarahwooders
