### ISSUE TITLE
MemGPT gets stuck thinking forever

### ISSUE THREAD

**Issue by Maxzurek** [cpacker/MemGPT#506]
**Describe the bug**
Sometimes, after asking a few questions to the AI, it gets stuck "thinking". I have to stop the LLM back-end manualy everytime to end the loop

**Expected behavior**
Should never be stuck in a loop

**Additional context**
MemGPT config file:
```
[defaults]
preset = memgpt_docs
persona = memgpt_doc
human = basic

[model]
model_endpoint = http://localhost:5000
model_endpoint_type = webui
model_wrapper = airoboros-l2-70b-2.1
context_window = 4096

[embedding]
embedding_endpoint_type = local
embedding_dim = 384
embedding_chunk_size = 300

[archival_storage]
type = local

[version]
memgpt_version = 0.2.4
```

**How did you install MemGPT?**

- From the official package `pip install pymemgpt`

**Your setup (please complete the following information)**

- Windows 11
- Where you're trying to run MemGPT from
  - cmd.exe?
- Your python version - 3.11.3
-  If you installed with `pip install pymemgpt`:
  - version 0.2.4

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- The exact model you're trying to use (link to the HuggingFace page you downloaded it from)
  - [dolphin-2.2.1-mistral-7B-AWQ](https://huggingface.co/TheBloke/dolphin-2.2.1-mistral-7B-AWQ)
- WebUI parameters
  - max_seq_len=4096
  - max_new_tokens=4096
  - temperature=0.3
- The local LLM backend you are using 
  - web UI
- Your hardware for the local LLM backend 
  - local computer: RTX3080 12VRAM, i7-9700K, 32GB RAM 3200MHZ, Samsung SSD 980
- Your hardware for the MemGPT command 
  - same computer as the local LLM backend

**Additional info**
- A document was attached to the agent
- I get the same bug using these models
  - [OpenHermes-2.5-Mistral-7B-AWQ](https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-AWQ)
  - [dolphin-2.1-mistral-7b-Q6_K-GGUF](https://huggingface.co/TheBloke/dolphin-2.1-mistral-7B-GGUF)
    - same parameters for both models

**MemGPT debug logs**

```
🤖 Yes, I am here and ready to assist. What can I do for you today?
⚡🟢 [function] Success: None
last response total_tokens (0) < 3072.0
InMemoryStateManager.append_to_messages
> Enter your message: Can you give me a short summarization of the document I-15-1 in your archival m
emory?
[A[KUsing model webui, endpoint: http://localhost:5000
💭 Searching archival memory for summarization of document I-15-1.
⚡🧠 [function] updating memory with archival_memory_search
'page'
{'query': 'I-15-1 summarization'}
⚡🟢 [function] Success: Showing 5 of 5 results (page 0/0): ["timestamp: 2023-11-24 06:55:10 PM ,
memory: Pour l'application du pr\u00e9sent article, un agent immobilier r\u00e9gi par la Loi sur le
courtage immobilier\n(chapitre C-73.1) est assimil\u00e9 \u00e0 un interm\u00e9diaire de march\u00e9
dont les activit\u00e9s sont r\u00e9gies par le\ngouvernement.\n\n1989, c. 48, a. 42; 1991, c. 37, a.
169.\n\n43. Les articles 35, 36, 37 et 37.1 s'appliquent, compte tenu des adaptations
n\u00e9cessaires, aux cabinets\nmultidisciplinaires titulaires d\u2019un certificat d\u00e9livr\u00e9
par l'inspecteur g\u00e9n\u00e9ral.\n\n\u00c0 cette fin, le paragraphe 4\u00b0 de l\u2019article 35
doit se lire de la fa\u00e7on suivante:\n\n\u00ab4\u00b0 enfreint la pr\u00e9sente loi ou la Loi sur
le courtage immobilier (chapitre C-73.1) ou les r\u00e8glements pris\npar le gouvernement pour leur
application. \u00bb.\n1989, c. 48, a. 43; 1991, c. 37, a. 170; 1997, c. 43, a.", "timestamp:
2023-11-24 06:55:10 PM , memory: L'Association peut \u00e9galement d\u00e9terminer, par
r\u00e9solution de son conseil d\u2019administration, une\naugmentation de la cotisation \u00e9tablie
en vertu du premier alin\u00e9a, lorsque cette augmentation est requise pour\npermettre \u00e0
l'Association d'assumer ses responsabilit\u00e9s en mati\u00e8re disciplinaire et d'inspection.
Cette\nr\u00e9solution est soumise \u00e0 l\u2019approbation de l'inspecteur
g\u00e9n\u00e9ral.\n\n1989, c. 48, a. 104.\n\n105. Les affaires de l'Association sont
administr\u00e9es par un conseil d'administration compos\u00e9 d\u2019au moins\n11
administrateurs.\n1989, c. 48, a. 105.\n\n106. Les administrateurs sont \u00e9lus par l'assembl\u00e9eg\u00e9n\u00e9rale annuelle de l'Association parmi ses\nsoci\u00e9taires.\n1989, c. 48, a.
106.\n\n107.", "timestamp: 2023-11-24 06:55:10 PM , memory: Le pouvoir r\u00e9glementaire du
gouvernement portant sur les mati\u00e8res vis\u00e9es aux articles 11, 23 \u00e0 25 et\n40 \u00e0 48
s'exerce, \u00e0 l\u2019\u00e9gard des courtiers en valeurs, des conseillers en valeurs ou de leurs
repr\u00e9sentants, en\nvertu de la Loi sur les valeurs mobili\u00e8res (chapitre V-1.1).\n\n1989, c.
48, a. 39.\n\nRemplac\u00e9 le 1\u00b0 octobre 1999\n\u00a9 \u00c9diteur officiel du Qu\u00e9bec
1-15.1/9 sur 41\n\n\n\nSECTION IV\n\nDISPOSITIONS COMMUNES AUX INTERM\u00c9DIAIRES DE MARCH\u00c9\n\n$1. \u2014 Cumul et multidisciplinarit\u00e9\n\n40.  L'interm\u00e9diaire de march\u00e9 peut, aux finsd'exercer ses activit\u00e9s dans plus d\u2019une discipline, cumuler les\ndivers certificats
d\u00e9livr\u00e9s conform\u00e9ment \u00e0 la pr\u00e9sente loi.\n1989, c. 48, a. 40.\n\n41.",
"timestamp: 2023-11-24 06:55:10 PM , memory: Le comit\u00e9 de surveillance de l\u2019Association\ndesinterm\u00e9diaires en assurance de personnes du Qu\u00e9bec et le comit\u00e9 de surveillance de
l'Association des\ncourtiers d\u2019assurances de la province de Qu\u00e9bec ex\u00e9cutent leurs
fonctions \u00e0 l\u2019\u00e9gard de leurs soci\u00e9taires\nrespectifs.\n\n1989, c. 48, a.
137.\n\n138. Un comit\u00e9 de surveillance a pour mission d'examiner la conduite des
interm\u00e9diaires de march\u00e9 en\nassurance, d\u2019enqu\u00eater sur toute question se
rapportant \u00e0 la discipline des interm\u00e9diaires de march\u00e9 en\nassurance et, s\u2019il y alieu, de porter plainte devant le comit\u00e9 de discipline.\n\n1989, c. 48, a. 138.\n\n139. Un
comit\u00e9 de surveillance est compos\u00e9 d\u2019au moins trois membres dont son pr\u00e9sident.
Les membres\nsont d\u00e9sign\u00e9s par l'association ou le conseil, selon le cas.\n1989, c. 48, a.
139,\n\n140.", "timestamp: 2023-11-24 06:55:10 PM , memory: 406.1-406.4).\n1989, c. 48, a.
245.\n\n246. (Inop\u00e9rant, 1990, c. 4, a. 90).\n1989, c. 48, a. 246.\n\n247. (Inop\u00e9rant, 1990,c. 4, a. 92).\n1989, c. 48, a. 247.\n\n248. (Modification int\u00e9gr\u00e9e au c. A-32, a.
420).\n1989, c. 48, a. 248.\n\n249. (Modification int\u00e9gr\u00e9e au c. B-1, a. 136).\n1989, c. 48,a. 249.\n\n250.  (Omis).\n1989, c. 48, a. 250.\n\n251. (Modification int\u00e9gr\u00e9e au c. N-1.1,
a. 77).\n1989, c. 48, a. 251.\n\n252. (Modification int\u00e9gr\u00e9e au c. P-30, a. 62).\n1989, c.
48, a. 252.\n\n253. (Modification int\u00e9gr\u00e9e au c. R-2.2, a. 6)."]
last response total_tokens (0) < 3072.0
InMemoryStateManager.append_to_messages
> Enter your message: Thank you
[A[KUsing model webui, endpoint: http://localhost:5000
step() failed
user_message = {"type": "user_message", "message": "Thank you", "time": "2023-11-24 06:55:38 PM "}
error = Request exceeds maximum context length (5325 > 4096 tokens)
MESSAGE_SUMMARY_TRUNC_TOKEN_FRAC=0.75
MESSAGE_SUMMARY_TRUNC_KEEP_N_LAST=3
token_counts=[239, 390, 46, 260, 61, 49, 57, 72, 313, 45, 56, 46]
message_buffer_token_count=3784
desired_token_count_to_summarize=2838
len(candidate_messages_to_summarize)=12
Selected cutoff 12 was a 'user', shifting one...
Attempting to summarize 11 messages [1:12] of 16
Using model webui, endpoint: http://localhost:5000
summarize_messages gpt reply: {'message': {'role': 'assistant', 'content': "The user initiates a
conversation with the assistant seeking to identify the contents of 'Chapitre 1, Article 8' from
document I-15-1 while specifying that the language is French. Subsequent to this conversation, the
assistant helps the user identify key phrases, and provides document summarization, classification,
and structure information. The assistant also flags sensitive or confidential phrases that may
possibly be present in the document, checking for completeness, consistency, and readability, and
providing the user with a summary."}, 'finish_reason': 'stop'}
Got summary: The user initiates a conversation with the assistant seeking to identify the contents of
'Chapitre 1, Article 8' from document I-15-1 while specifying that the language is French. Subsequent
to this conversation, the assistant helps the user identify key phrases, and provides document
summarization, classification, and structure information. The assistant also flags sensitive or
confidential phrases that may possibly be present in the document, checking for completeness,
consistency, and readability, and providing the user with a summary.
Packaged into message: {"type": "system_alert", "message": "Note: prior messages (47 of 51 total
messages) have been hidden from view due to conversation memory constraints.\nThe following is a
summary of the previous 11 messages:\n The user initiates a conversation with the assistant seeking toidentify the contents of 'Chapitre 1, Article 8' from document I-15-1 while specifying that the
language is French. Subsequent to this conversation, the assistant helps the user identify key
phrases, and provides document summarization, classification, and structure information. The assistantalso flags sensitive or confidential phrases that may possibly be present in the document, checking
for completeness, consistency, and readability, and providing the user with a summary.", "time":
"2023-11-24 06:55:46 PM "}
InMemoryStateManager.prepend_to_message
Ran summarizer, messages length 16 -> 6
Using model webui, endpoint: http://localhost:5000
step() failed
user_message = {"type": "user_message", "message": "Thank you", "time": "2023-11-24 06:55:38 PM "}
error = Request exceeds maximum context length (4202 > 4096 tokens)
MESSAGE_SUMMARY_TRUNC_TOKEN_FRAC=0.75
MESSAGE_SUMMARY_TRUNC_KEEP_N_LAST=3
token_counts=[178, 46]
message_buffer_token_count=2374
desired_token_count_to_summarize=1780
len(candidate_messages_to_summarize)=2
Selected cutoff 2 was a 'user', shifting one...
Attempting to summarize 1 messages [1:2] of 6
Using model webui, endpoint: http://localhost:5000
summarize_messages gpt reply: {'message': {'role': 'assistant', 'content': "The user discussed
identifying the contents of 'Chapitre 1, Article 8' from document I-15-1 in French. They requested
assistance in identifying key phrases and document summarization, classification, and structure
information. The assistant also highlighted potential sensitive or confidential phrases and ensured
completeness, consistency, and readability for the user."}, 'finish_reason': 'stop'}
Got summary: The user discussed identifying the contents of 'Chapitre 1, Article 8' from document
I-15-1 in French. They requested assistance in identifying key phrases and document summarization,
classification, and structure information. The assistant also highlighted potential sensitive or
confidential phrases and ensured completeness, consistency, and readability for the user.
Packaged into message: {"type": "system_alert", "message": "Note: prior messages (48 of 52 total
messages) have been hidden from view due to conversation memory constraints.\nThe following is a
summary of the previous 1 messages:\n The user discussed identifying the contents of 'Chapitre 1,
Article 8' from document I-15-1 in French. They requested assistance in identifying key phrases and
document summarization, classification, and structure information. The assistant also highlighted
potential sensitive or confidential phrases and ensured completeness, consistency, and readability forthe user.", "time": "2023-11-24 06:55:52 PM "}
InMemoryStateManager.prepend_to_message
Ran summarizer, messages length 6 -> 6
Using model webui, endpoint: http://localhost:5000
step() failed
user_message = {"type": "user_message", "message": "Thank you", "time": "2023-11-24 06:55:38 PM "}
error = Request exceeds maximum context length (4146 > 4096 tokens)
MESSAGE_SUMMARY_TRUNC_TOKEN_FRAC=0.75
MESSAGE_SUMMARY_TRUNC_KEEP_N_LAST=3
token_counts=[122, 46]
message_buffer_token_count=2318
desired_token_count_to_summarize=1738
len(candidate_messages_to_summarize)=2
Selected cutoff 2 was a 'user', shifting one...
Attempting to summarize 1 messages [1:2] of 6
Using model webui, endpoint: http://localhost:5000
summarize_messages gpt reply: {'message': {'role': 'assistant', 'content': 'The AI has been analyzing
chapter 1, article 8 and ensuring document quality and consistency. However, due to memory
constraints, I am unable to show you the full conversation. This has affected the display of 1
previous message out of 57.'}, 'finish_reason': 'stop'}
Got summary: The AI has been analyzing chapter 1, article 8 and ensuring document quality and
consistency. However, due to memory constraints, I am unable to show you the full conversation. This
has affected the display of 1 previous message out of 57.
Packaged into message: {"type": "system_alert", "message": "Note: prior messages (54 of 58 total
messages) have been hidden from view due to conversation memory constraints.\nThe following is a
summary of the previous 1 messages:\n The AI has been analyzing chapter 1, article 8 and ensuring
document quality and consistency. However, due to memory constraints, I am unable to show you the fullconversation. This has affected the display of 1 previous message out of 57.", "time": "2023-11-24
06:56:27 PM "}
InMemoryStateManager.prepend_to_message
Ran summarizer, messages length 6 -> 6
Using model webui, endpoint: http://localhost:5000
An exception ocurred when running agent.step():
Traceback (most recent call last):
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 586, in step
    response = self.get_ai_reply(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 801, in get_ai_reply
    raise e
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 783, in get_ai_reply
    response = chat_completion_with_backoff(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 57, in wrapper
    raise e
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 116, in chat_completion_with_backoff
    return get_chat_completion(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\local_llm\chat_completion_proxy.py", line 88, in get_chat_completion
    result = get_webui_completion(endpoint, prompt, context_window, grammar=grammar_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\local_llm\webui\api.py", line 16, in get_webui_completion
    raise Exception(f"Request exceeds maximum context length ({prompt_tokens} > {context_window} tokens)")
Exception: Request exceeds maximum context length (5325 > 4096 tokens)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 586, in step
    response = self.get_ai_reply(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 801, in get_ai_reply
    raise e
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 783, in get_ai_reply
    response = chat_completion_with_backoff(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 57, in wrapper
    raise e
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 116, in chat_completion_with_backoff
    return get_chat_completion(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\local_llm\chat_completion_proxy.py", line 88, in get_chat_completion
    result = get_webui_completion(endpoint, prompt, context_window, grammar=grammar_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\local_llm\webui\api.py", line 16, in get_webui_completion
    raise Exception(f"Request exceeds maximum context length ({prompt_tokens} > {context_window} tokens)")
Exception: Request exceeds maximum context length (4145 > 4096 tokens)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 586, in step
    response = self.get_ai_reply(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 801, in get_ai_reply
    raise e
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 783, in get_ai_reply
    response = chat_completion_with_backoff(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 57, in wrapper
    raise e
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 116, in chat_completion_with_backoff
    return get_chat_completion(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\local_llm\chat_completion_proxy.py", line 88, in get_chat_completion
    result = get_webui_completion(endpoint, prompt, context_window, grammar=grammar_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\local_llm\webui\api.py", line 16, in get_webui_completion
    raise Exception(f"Request exceeds maximum context length ({prompt_tokens} > {context_window} tokens)")
Exception: Request exceeds maximum context length (4135 > 4096 tokens)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mcesa\MemGPT\memgpt\main.py", line 608, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\main.py", line 584, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning = memgpt_agent.step(
                                                                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 652, in step
    return self.step(user_message, first_message=first_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 652, in step
    return self.step(user_message, first_message=first_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 652, in step
    return self.step(user_message, first_message=first_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 48 more times]
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 649, in step
    self.summarize_messages_inplace()
  File "C:\Users\mcesa\MemGPT\memgpt\agent.py", line 719, in summarize_messages_inplace
    summary = summarize_messages(agent_config=self.config, message_sequence_to_summarize=message_sequence_to_summarize)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\memory.py", line 141, in summarize_messages
    response = chat_completion_with_backoff(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 57, in wrapper
    raise e
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\openai_tools.py", line 116, in chat_completion_with_backoff
    return get_chat_completion(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcesa\MemGPT\memgpt\local_llm\chat_completion_proxy.py", line 106, in get_chat_completion
    raise LocalLLMConnectionError(f"Unable to connect to endpoint {endpoint}")
memgpt.errors.LocalLLMConnectionError: Unable to connect to endpoint http://localhost:5000
? Retry agent.step()? No
> Enter your message:
[A[KEmpty input received. Try again!
> Enter your message: /exit
[A[KSaved state to <_io.BufferedWriter name='C:\\Users\\mcesa\\.memgpt\\agents\\agent_1\\persistence_manager\\2023-11-24_07_00_03_PM_.persistence.pickle'>
Finished.

```

**Comment by Maxzurek** [comment]
It seems like the bug happens when the max context length is reached. Output from the back-end webui LLM:
```
Output generated in 49.57 seconds (2.46 tokens/s, 122 tokens, context 3253, seed 1748486723)
Llama.generate: prefix-match hit
Output generated in 48.15 seconds (2.20 tokens/s, 106 tokens, context 3584, seed 605406240)
Llama.generate: prefix-match hit
Output generated in 48.96 seconds (1.82 tokens/s, 89 tokens, context 4104, seed 1847581758)
Llama.generate: prefix-match hit
Output generated in 45.96 seconds (1.54 tokens/s, 71 tokens, context 4254, seed 424124905)
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3399.31 ms
llama_print_timings:      sample time =     168.16 ms /    78 runs   (    2.16 ms per token,   463.84 tokens per second)
llama_print_timings: prompt eval time =   15387.74 ms /  2167 tokens (    7.10 ms per token,   140.83 tokens per second)
llama_print_timings:        eval time =   17300.74 ms /    77 runs   (  224.68 ms per token,     4.45 tokens per second)
llama_print_timings:       total time =   33015.70 ms
Output generated in 33.35 seconds (2.31 tokens/s, 77 tokens, context 2582, seed 1871483229)
Llama.generate: prefix-match hit
Output generated in 52.75 seconds (1.35 tokens/s, 71 tokens, context 4407, seed 198712088)
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3399.31 ms
llama_print_timings:      sample time =     295.58 ms /   137 runs   (    2.16 ms per token,   463.49 tokens per second)
llama_print_timings: prompt eval time =    3859.64 ms /   560 tokens (    6.89 ms per token,   145.09 tokens per second)
llama_print_timings:        eval time =   29445.99 ms /   136 runs   (  216.51 ms per token,     4.62 tokens per second)
llama_print_timings:       total time =   33880.00 ms
Output generated in 34.23 seconds (3.97 tokens/s, 136 tokens, context 642, seed 1937934647)
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3399.31 ms
llama_print_timings:      sample time =     215.19 ms /   100 runs   (    2.15 ms per token,   464.71 tokens per second)
llama_print_timings: prompt eval time =    2636.36 ms /   464 tokens (    5.68 ms per token,   176.00 tokens per second)
llama_print_timings:        eval time =   21215.26 ms /    99 runs   (  214.30 ms per token,     4.67 tokens per second)
llama_print_timings:       total time =   24266.63 ms
Output generated in 24.60 seconds (4.02 tokens/s, 99 tokens, context 521, seed 193129501)
Llama.generate: prefix-match hit

llama_print_timings:        load time =    3399.31 ms
llama_print_timings:      sample time =     231.15 ms /   107 runs   (    2.16 ms per token,   462.90 tokens per second)
llama_print_timings: prompt eval time =    2335.80 ms /   429 tokens (    5.44 ms per token,   183.66 tokens per second)
llama_print_timings:        eval time =   22963.40 ms /   106 runs   (  216.64 ms per token,     4.62 tokens per second)
llama_print_timings:       total time =   25746.86 ms
Output generated in 26.07 seconds (4.07 tokens/s, 106 tokens, context 484, seed 124149250)
Llama.generate: prefix-match hit
```

Am I missing something? Did I not configure the webui properly?

**Comment by marschou1989** [comment]
I met this problem too, I can't even pass the first thinking
![Uploading 1701053730490.png…]()

**Comment by cpacker** [comment]
Sorry for the delay here (in the future if you have Discord feel free to ping me on #support).

This is caused by the first message not passing "first message verification", which tries to make sure that the first message is both a `send_message` function call, and has inner monologue. That's likely why you're getting stuck on a thinking loop.

If you'd like to bypass this check, you can run with `--no-verify`. However, I'd recommend using an open LLM that doesn't have this problem - eg dolphin 2.2.1 or openhermes 2.5. You can check the Discord #model-chat page to see up-to-date model recommendations.
