### ISSUE TITLE
/attach command ... when I try attach something where is nothing loaded

### ISSUE THREAD

**Issue by zdendos** [cpacker/MemGPT#511]
> Enter your message: /attach
Traceback (most recent call last):
  File "/Users/zdendos/__developing__/__local__/MemGPT/main.py", line 3, in <module>
    app()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt310/lib/python3.10/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt310/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt310/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt310/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt310/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt310/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt310/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt310/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt310/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/zdendos/__developing__/__local__/MemGPT/memgpt/cli/cli.py", line 205, in run
    run_agent_loop(memgpt_agent, first, no_verify, config)  # TODO: add back no_verify
  File "/Users/zdendos/__developing__/__local__/MemGPT/memgpt/main.py", line 460, in run_agent_loop
    data_source = questionary.select("Select data source", choices=data_source_options).ask()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/memgpt310/lib/python3.10/site-packages/questionary/prompts/select.py", line 133, in select
    raise ValueError("A list of choices needs to be provided.")
ValueError: A list of choices needs to be provided.

This only happend, when I will forget call "python3 main.py load directory ..." before I call "/attach" command

**Comment by zdendos** [comment]
And there is opposite issue. I am able to attach same source many times ( I forgot, that I attached it already ). Each time will increase number of embeddings.

**Comment by sarahwooders** [comment]
Thanks for reporting this! You need to run `memgpt load ...` to load in a data source before you can attach it to an agent. However, we definitely should throw a warning instead of an error (fixed in  #513). 

We don't really keep metadata about loaded data (this will be fixed soon), so if you run `/attach` multiple times, it'll just ingest the embeddings into the agent's archival memory and you'll have duplicated data.
