### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by aboodebaker** [cpacker/MemGPT#52]
why do i get this error: 

`C:\Users\yasee.STUDY-COMPUTER\OneDrive\Documents\VS Code\MemGPT>python main.py
Traceback (most recent call last):
  File "C:\Users\yasee.STUDY-COMPUTER\OneDrive\Documents\VS Code\MemGPT\main.py", line 8, in <module>
    import readline
  File "C:\Users\yasee.STUDY-COMPUTER\AppData\Local\Programs\Python\Python311\Lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
         ^^^^^^^^^^
  File "C:\Users\yasee.STUDY-COMPUTER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\yasee.STUDY-COMPUTER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\yasee.STUDY-COMPUTER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\yasee.STUDY-COMPUTER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
           ^^^^^^^^^^^^^^
  File "C:\Users\yasee.STUDY-COMPUTER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'`

**Comment by gressen** [comment]
This is a solution that worked for me. Go to your py3k_compat.py file:
`C:\Users\yasee.STUDY-COMPUTER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\py3k_compat.py`
and change line 8 (or close) from
`        return isinstance(x, collections.Callable)`
to
`        return isinstance(x, collections.abc.Callable)`

**Comment by briancunning** [comment]
Thanks, I had that issue too and your solution worked. What is the long term fix. Is it a bug in the pyreadline?

**Comment by briancunning** [comment]
I followed the instructions here to install which incolved setting up a conda environment and it worked out of the box. https://www.youtube.com/watch?v=QQ2QOPWZKVc&t=1581

**Comment by vcpandya** [comment]
You can directly import pyreadline3 (uninstall pyreadline) and it will work as well.

**Comment by cpacker** [comment]
https://github.com/cpacker/MemGPT#running-memgpt-locally

Updated README to use `pyreadline3`, which should fix this issue.
