### ISSUE TITLE
UnicodeDecodeError when talking with docx files

### ISSUE THREAD

**Issue by mortenfj** [cpacker/MemGPT#55]
When i try to input a bunch of .docx files i get this error:
(env_MemGPT) user@machine:~/projects/MemGPT$ python3 main.py --archival_storage_files="/home/user/projects/docs/FDS_docs/*.docx" --persona=memgpt_doc --human=basic
Running... [exit by typing '/exit']
Traceback (most recent call last):
  File "/home/user/projects/MemGPT/main.py", line 290, in <module>
    app.run(run)
  File "/home/user/projects/MemGPT/env_MemGPT/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/user/projects/MemGPT/env_MemGPT/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/user/projects/MemGPT/main.py", line 288, in run
    loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/projects/MemGPT/main.py", line 55, in main
    archival_database = utils.prepare_archival_index_from_files(FLAGS.archival_storage_files)
  File "/home/user/projects/MemGPT/memgpt/utils.py", line 114, in prepare_archival_index_from_files
    return chunk_files(files, tkns_per_chunk, model)
  File "/home/user/projects/MemGPT/memgpt/utils.py", line 165, in chunk_files
    chunks = [c for c in chunk_file(file, tkns_per_chunk, model)]
  File "/home/user/projects/MemGPT/memgpt/utils.py", line 165, in <listcomp>
    chunks = [c for c in chunk_file(file, tkns_per_chunk, model)]
  File "/home/user/projects/MemGPT/memgpt/utils.py", line 129, in chunk_file
    lines = [l for l in read_in_chunks(f, tkns_per_chunk*4)]
  File "/home/user/projects/MemGPT/memgpt/utils.py", line 129, in <listcomp>
    lines = [l for l in read_in_chunks(f, tkns_per_chunk*4)]
  File "/home/user/projects/MemGPT/memgpt/utils.py", line 96, in read_in_chunks
    data = file_object.read(chunk_size)
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 14: invalid continuation byte

Hope this gives a clue about what could be wrong.
I'm on Ubuntu, and the projects works just fine on other folders containing .txt files.

**Comment by eskelley** [comment]
I'm also on Ubuntu and having the same issue, but with the example SQL database provided. Python 3.9.13.

**Comment by cpacker** [comment]
_Closed due to inactivity - feel free to reopen if still unresolved_
