### ISSUE TITLE
memgpt load directory failure

### ISSUE THREAD

**Issue by cgf1** [cpacker/MemGPT#711]
I just updated memgpt via:

pip install -e '.[local]'

I removed $HOME/.memgpt

and did:  % memgpt quickstart

Now I've  found that the "memgpt load" command failed.

(.venv) % memgpt load directory --name realed --input-dir /home/XXX/realed/data --recursive
LLM is explicitly disabled. Using MockLLM.
LLM is explicitly disabled. Using MockLLM.
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 247.98it/s]
Generating embeddings: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 85/85 [00:09<00:00,  8.62it/s]
  0%|                                                                                                                                                            | 0/85 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/src/memgpt/.venv/bin/memgpt", line 8, in <module>
    sys.exit(app())
  File "/usr/src/memgpt/.venv/lib/python3.10/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/usr/src/memgpt/.venv/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/src/memgpt/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/src/memgpt/.venv/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/usr/src/memgpt/.venv/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/usr/src/memgpt/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/src/memgpt/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/src/memgpt/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/src/memgpt/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/memgpt/.venv/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/src/memgpt/memgpt/cli/cli_load.py", line 106, in load_directory
    store_docs(name, docs)
  File "/usr/src/memgpt/memgpt/cli/cli_load.py", line 48, in store_docs
    len(node.embedding) == config.embedding_dim
AssertionError: Expected embedding dimension 1536, got 4: {'object': 'list', 'data': [{'object': 'embedding', 'embedding': [0.028163107, -0.05077997, 0.0070294114, -0.017297922, -0.04732493, 0.022435017, -0.05218926, 0.00862623, -0.032641016, 0.011774406, 0.038164534, -0.03891464, -0.0023597113, 0.02959513, 0.0030174756, 0.019230014, -0.020855246, 0.03975567, 0.0025358729, -0.06610034, 0.03800542, -0.028254028, -0.0016721134, -0.010103714, -0.005830377, -0.030731654, -0.047597695, -0.025708212, -0.06550934, 0.035641447, -0.024094345, 0.01660464, 0.034527652, -0.048961528, 0.01658191, -0.023548812, -0.04564287, -0.04859784, 0.03668705, -0.004102858, 0.017184269, 0.018502638, -0.052916635, 0.043301627, 0.018707212, 0.00024630642, -0.024185266, -0.025480906, 0.026344664, -0.020650672, 0.023321507, -0.049461596, 0.025276331, 0.03534595, -0.04032393, 0.023957962, -0.012274478, 0.041392267, 0.0063247653, -0.003352...

**Comment by cpacker** [comment]
Should be fixed by #725 !
