### ISSUE TITLE
`memgpt load` - Unable to load new data sources

### ISSUE THREAD

**Issue by curVV** [cpacker/MemGPT#764]
**Describe the bug**
Errors when uploading documents using command `memgpt load`

Output when loading a pdf with command `memgpt load directory --name abc --input-files abc.pdf`:
```
Parsing nodes: 100%|████████████████████████████████████████████████████████████████████| 39/39 [00:00<00:00, 116.95it/s]
Generating embeddings:   0%|                                                                     | 0/371 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/memgpt/venv/lib/python3.11/site-packages/memgpt/embeddings.py", line 62, in _call_api
    embedding = response_json["data"][0]["embedding"]
                ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/memgpt/venv/bin/memgpt", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/memgpt/venv/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/memgpt/cli/cli_load.py", line 109, in load_directory
    store_docs(name, docs)
  File "/memgpt/venv/lib/python3.11/site-packages/memgpt/cli/cli_load.py", line 40, in store_docs
    index = VectorStoreIndex.from_documents(docs, service_context=service_context, show_progress=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 106, in from_documents
    return cls(
           ^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 52, in __init__
    super().__init__(
  File "/memgpt/venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 262, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **insert_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 243, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "/memgpt/venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 196, in _add_nodes_to_index
    nodes_batch = self._get_node_with_embedding(nodes_batch, show_progress)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 104, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
                      ^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/llama_index/indices/utils.py", line 137, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 256, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/memgpt/embeddings.py", line 112, in _get_text_embeddings
    embeddings = [self._get_text_embedding(text) for text in texts]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/memgpt/embeddings.py", line 112, in <listcomp>
    embeddings = [self._get_text_embedding(text) for text in texts]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/memgpt/embeddings.py", line 108, in _get_text_embedding
    embedding = self._call_api(text)
                ^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/memgpt/embeddings.py", line 64, in _call_api
    raise TypeError(f"Got back an unexpected payload from text embedding function, response=\n{response_json}")
TypeError: Got back an unexpected payload from text embedding function, response=
{'message': 'Input validation error: `inputs` must have less than 512 tokens. Given: 1664', 'code': 413, 'type': 'Validation'}
Generating embeddings:   2%|█▍                                                           | 9/371 [00:02<01:44,  3.46it/s]
```

When loading txt file with `memgpt load directory --name abctxt --input-files abc.txt ` :
```
Parsing nodes: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 127.72it/s]
Generating embeddings: 100%|███████████████████████████████████████████████████████████████| 8/8 [00:06<00:00,  1.20it/s]
  0%|                                                                                              | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/memgpt/venv/bin/memgpt", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/memgpt/venv/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/memgpt/venv/lib/python3.11/site-packages/memgpt/cli/cli_load.py", line 109, in load_directory
    store_docs(name, docs)
  File "/memgpt/venv/lib/python3.11/site-packages/memgpt/cli/cli_load.py", line 51, in store_docs
    len(node.embedding) == config.embedding_dim
AssertionError: Expected embedding dimension 1536, got 1024: [-0.005684822, -0.05186776, 0.0073819496, -0.015995149, -0.011868799, 0.0069548944, -0.035340182, -0.018058322, -0.01315551, 0.008685299, 0.04421405, -0.046765286, 0.015651286, 0.046188485, 0.014286928, 0.02336046, -0.00978344, 0.013554834, 0.0023709869, -0.043770358, -0.0105765425, 0.006710863, -0.009151177, 0.0018884701, -0.0075816116, -0.026266651, -0.015850948, -0.016982365, -0.00050851423, 0.025911696, 0.0057291915, -0.006771871, 0.04596664, -0.031701896, 0.051069114, 0.020531913, -0.023582306, -0.039998963, 0.026444128, -0.0131000485, -0.0074817804, 0.038667884, -0.04574479, 0.026266651, 0.0152408695, 0.030459553, -0.032278698, -0.024869017, -0.023826336, -0.043437585, 0.032278698, -0.040908534, 0.03709277, 0.013577019, -0.02664379, -0.0039849216, 0.032278698, 0.059809875, -0.03751428, 0.01771446, 0.040952902, 0.019577973, 0.002430608, -0.00196473, 0.041330043, 0.0022614498, 0.044435896, 0.006084146, 0.033321377, 0.021452578, -0.061140954, -0.063936226, 0.0152408695, 0.023493567, -0.009938733, -0.012556524, -0.016560856, 0.00045859875, 0.027886132, 0.06713081, -0.046898395, -0.023671044, -0.01648321, 0.0076869885, 0.009278739, 0.0013858487, -0.0014517094, 0.00874076, 0.012545432, 0.06140717, 0.025046494, -0.012745094, 0.02568985, 0.020698298, -0.049693663, -0.021796439, -0.03904502, 0.033587594, 0.030526107, -0.028107978, -0.027775208, -0.042528015, -0.00095948705, -0.016394472, -0.0153407, -0.060652893, -0.025002124, 0.032256514, -0.06930491, -0.010049656, -0.0064557395, -0.019633435, -0.034940857, -0.019189741, -0.029283766, 0.03746991, 0.042439274, -0.02217358, 0.028795702, 0.023826336, 0.031080725, 0.0036105553, -0.031369124, -0.033032976, -0.038956285, 0.047342088, -0.02864041, -0.0048029814, 0.02864041, 0.024425322, 0.047741413, -0.016804889, 0.016893627, -0.0075594266, 0.036870923, 0.070680365, -0.030991986, -0.07263261, 0.0063281776, 0.0486288, -0.018246893, -0.023671044, 0.036671262, -0.025002124, 0.022872396, -0.054308075, -0.0039155944, -0.013599204, -0.094684176, -0.032611467, -0.019999482, -0.0011348845, -0.031280387, -0.016139349, 0.025556741, -0.063758746, 0.009417393, -0.010254865, -0.01908991, 0.015551454, 0.025578925, 0.017215304, -0.019411588, 0.0141649125, -0.0029311497, 0.02502431, 0.025401449, 0.0042428183, 0.002878461, 0.013699034, -0.0005580831, 0.028041424, 0.050314836, 0.017359504, -0.00900143, -0.032278698, 0.046144117, -0.023338275, 0.013321895, 0.029217212, -0.009556047, 0.010826119, -0.03318827, -0.03751428, -0.02868478, 0.044790853, 0.024114737, -0.01108679, -0.0076869885, -0.0662878, -0.042683307, -0.014253652, -0.03567295, 0.040575765, -0.02801924, -0.013943066, -0.028507303, -0.013998528, -0.036626894, 0.04030955, 0.051645916, 0.02146367, -0.020620652, -0.03746991, 0.00892933, 0.0038185366, 0.030881062, 0.02212921, -0.018269077, 0.019256294, 0.006034231, 0.007703627, 0.01108679, -0.041684996, -0.024580617, 0.01030478, 0.023160797, 0.0046781925, -0.00022825947, 0.020953422, -0.03862351, 0.038068894, 0.033410113, -0.047342088, -0.011713507, 0.024846831, -0.042328354, -0.025578925, 0.027863948, -0.022107026, 0.029749645, 0.06384748, -0.03917813, -0.054973617, -0.04854006, -0.022395426, 0.021119807, -0.031369124, 0.047563937, 0.04292734, 0.030614845, 0.042483646, 0.029882751, -0.027087484, 0.0007216951, 0.03296642, 0.043104816, 0.009117899, 0.028995365, 0.06389185, -0.008258244, 0.015418347, -0.011890984, -0.02568985, -0.0025872872, 0.037891418, 0.038778804, -0.04840695, -0.010265957, 0.06739703, 0.025601111, -0.019611249, -0.006683132, -0.025601111, -0.020387713, -0.012456693, 0.021119807, 0.008402444, 0.08297067, -0.0036743362, 0.009395208, 0.032167774, 0.016228087, -0.02939469, -0.030215522, 0.02826327, -0.0074429573, -0.020620652, 0.037669573, -0.005149617, 0.027398068, 0.022761473, 0.038290743, 0.051512808, -0.04654344, 0.023293905, -0.0013574245, 0.03764739, 0.07045852, 0.022828028, -0.0102049485, 0.020986699, 0.027597731, -0.014364575, -0.014730622, 0.030858878, -0.053465057, 0.011935353, 0.055284202, 0.004728108, 0.030503923, 0.0011646952, -0.033787254, -0.06406933, -0.021175269, -0.03693748, 0.03347667, -0.028174533, 0.019023355, 0.018513108, -0.03263365, -0.007864466, -0.061850864, 0.0033249275, -0.041485336, -0.021286191, -0.06473487, 0.010332511, -0.008896053, -0.008019758, 0.0064335545, 0.01952251, -0.028462933, -0.045522947, -0.050092988, 0.009278739, -0.033986915, -0.02593388, 0.013321895, 0.00037436633, -0.03451935, 0.009195547, 0.08381369, 0.011458383, -0.02668816, -0.034408424, 0.0064668315, -0.047475196, 0.028751334, 0.015473808, 0.023382643, 0.009994195, -0.031657524, -0.01704892, 0.0043925648, 0.03576169, 0.0035800512, -0.017403875, 0.023449197, 0.03006023, 0.031369124, 0.012146108, 0.0030892154, -0.049560554, -0.059011225, -0.024869017, 0.010382426, -0.040531393, 0.0013830756, 0.032189958, 0.060919106, 0.010964774, 0.08620963, -0.0016347329, 0.023471382, -0.023804152, 0.030282076, -0.03784705, 0.0024749774, 0.010848304, 0.0076481653, 0.02256181, 0.03558421, -0.08833936, -0.02046536, -0.028285455, 0.008241605, 0.042860784, 0.04658781, -0.013377356, 0.014220375, 0.060164828, 0.011336367, -0.031945925, -0.050226096, -0.0088017685, -0.03888973, -0.033654146, -0.0023418693, -0.017947398, -0.016693965, -0.0038850906, 0.017304044, -0.043304477, 0.012889294, -0.04326011, 0.031657524, -0.018479832, 0.007881104, 0.022739287, 0.04421405, 0.021208545, 0.022384332, 0.009966464, -0.025357079, -0.010537718, 0.06007609, 0.021386024, 0.0006953508, -0.023493567, -0.0156069165, 0.022550719, 0.010476711, 0.028662596, -0.013366264, 0.025401449, -0.004464665, 0.028418563, -0.024536246, -0.029283766, -0.0068994327, -0.011935353, 0.012123923, -0.021297283, 0.029904937, -0.013410633, 0.016827073, 0.01363248, -0.010837212, -0.044502452, 0.041862473, -0.048318215, -0.030881062, -0.034230947, 0.018646216, -0.0331439, 0.031369124, -0.0023987177, 0.018357815, -0.04467993, 0.04405876, 0.015784394, -0.0116469525, -0.032988608, 0.037203692, -0.010021925, -0.037580833, -0.01448659, -0.011558213, 0.048451323, -0.0029866113, -0.01648321, 0.028196717, -0.014420036, -0.0061728847, -0.04321574, -0.019356126, 0.01434239, -0.012201569, -0.00659994, -0.048051998, -0.031502232, 0.004223407, -0.027109668, -0.014042897, 0.00034871532, 0.02939469, 0.01481936, -0.018823694, 0.030148968, -0.024336584, -0.01400962, 0.04416968, 0.011613675, -0.028152348, 0.031657524, 0.04658781, 0.026066989, 0.015928594, 0.049649294, -0.017359504, -0.02844075, 0.02289458, 0.025822958, -0.054308075, 0.0056099487, -0.07072473, -0.0075594266, 0.023671044, 0.001719312, -0.04858443, 0.04416968, 0.043016076, -0.0017456564, 0.039821483, -0.025534557, -0.023404827, -0.012867109, -0.07196707, 0.007459596, 0.054396816, -0.054396816, 0.025623295, 0.025623295, 0.009544955, 0.059765503, -0.031901557, 0.0029671998, -0.031280387, 0.04425842, -0.009411847, -0.033077344, -0.026821267, 0.020520821, 0.023981629, 0.035894796, 0.025534557, 0.023781968, 0.025578925, -0.008624291, -0.022151394, 0.0040209717, 0.015751116, -0.0098444475, -0.0024430868, 0.012434509, 0.003568959, 0.03680437, -0.025778588, -0.035983536, -0.040531393, 0.0696155, -0.030836694, 0.042528015, 0.014131635, 0.009955371, -0.0050109625, -0.021885179, 0.0026704797, 0.023116427, 0.014120543, 0.033410113, 0.017681183, -0.023160797, -0.010881581, -0.02227341, -0.068284415, 0.028551672, 0.00059655966, -0.035273626, -0.0074485033, 0.0048002084, -0.06606595, -0.004004333, -0.03460809, 0.061007846, -0.045434207, 0.01752589, 0.055727895, -0.055905372, -0.0009879111, -0.004617185, 0.03347667, -0.010238226, -0.032655835, 0.03476338, -0.01628355, 0.012201569, -0.030792324, 0.042195246, 0.008036397, -0.016372288, 0.07325379, -0.024957756, -0.011369644, 0.033166084, 0.006877248, -0.00086520216, 0.029616537, -0.012090646, 0.0036992938, -0.0619396, 0.026444128, -0.023116427, -0.031701896, -0.010881581, -0.010815027, -0.01775883, 0.01800286, 0.044103127, 0.033454485, 0.055639155, 0.022195764, -0.036560338, 0.053065732, -0.022761473, 0.029527798, -0.040442657, 0.0012159973, 0.020909052, 0.0155958235, -0.008618745, 0.02968309, -0.0011279519, 0.014708437, 0.022395426, 0.026177913, 0.01628355, 0.01052108, 0.017359504, -0.031457864, 0.030836694, 0.034230947, 0.023848522, -0.01956688, 0.023826336, -0.040487025, -0.01386542, 0.03937779, 0.043149184, -0.015884224, 0.0568815, 0.030282076, 0.053243212, 0.009012523, -0.018579662, 0.019289572, -0.013743404, 0.03642723, 0.035916984, 0.00068044546, 0.0044813035, -0.018357815, 0.004303826, -0.023049874, -0.0075982497, -0.06207271, -0.065001085, 0.030592661, 0.02664379, 0.04416968, 0.030370815, -0.021064345, 0.026754713, -0.036338493, 0.010482257, -0.05328758, -0.032500543, 0.015429439, -0.03746991, -0.03780268, 0.037492093, -0.023449197, 0.017459337, 0.012334677, 0.005388102, 0.029616537, -0.012079554, 1.9259935e-05, -0.02963872, 0.052755147, 0.004583908, 0.021885179, -0.019932928, 0.014575329, 0.1298247, -0.012179385, 0.040553577, -0.0138210505, 0.02033225, 0.087185755, -0.024824647, 0.025002124, -0.0052023055, 0.02293895, 0.0141649125, 0.020975607, 0.029195027, 0.049471818, -0.023094242, 0.03671563, 0.032212142, -0.03551766, -0.020909052, -0.0048473505, 0.009023615, -0.021796439, -0.014941376, -0.009117899, 0.0030670308, 0.019777635, -0.061895233, -0.054796137, 0.010754019, 0.042594567, -0.006649855, 0.03755865, 0.030548293, -0.0039488715, -0.03263365, -0.05271078, -0.013244249, 0.038512588, 0.030104598, -0.018335631, 0.042106505, 0.064601764, -0.03600572, -0.0064945626, 0.039998963, -0.017104382, 0.00050851423, 0.015274147, 0.010493349, 0.015518177, 0.020576283, -0.03163534, -0.029705275, -0.012689632, -0.03924468, 0.008507822, 0.055861004, 0.014897007, 0.0029228304, -0.04574479, -0.0050054165, 0.0152297765, 0.027797394, 0.040952902, -0.04516799, -0.044502452, 0.0022212402, 0.047519565, 0.03975493, -0.022506349, 0.0270653, -0.044923957, -0.052222718, 0.01966671, -0.05679276, -0.006838425, 0.012534339, -0.011336367, -0.024447508, -0.016327918, -0.036205385, 0.0130889565, -0.029927121, -0.004822393, 0.009716886, -0.039777115, -0.045345467, 0.016738335, -0.016272455, -0.037824865, -0.038734436, 0.016583042, 0.018535294, 0.0062283464, 0.001437844, -0.0046116384, 0.009273193, 0.012290308, 0.0033887085, 0.02830764, 0.0074762343, 0.026177913, 0.0033110622, -0.02364886, -0.022362148, -0.036338493, 0.044768665, -0.032123405, 0.05129096, -0.013321895, 0.04425842, 0.026776899, 0.011746784, 0.030637031, -0.011253174, 0.007975389, -0.013887604, -0.035362367, 0.0078034583, 0.022395426, 0.048939385, -0.009411847, 0.032367434, 0.016305733, 0.0013109754, 0.014830452, 0.014275836, 0.016117163, -0.04487959, -0.0067607784, 0.041618444, -0.013710127, -0.022916766, -0.046055377, -0.030548293, 0.052755147, 0.0395109, 0.014874822, -0.007659258, 0.0015626327, -0.042261798, -0.057014607, -0.054263707, -0.0024583389, 0.01694909, 0.041330043, -0.023537936, 0.04783015, 0.029860567, 0.082482606, -0.03600572, -0.058434423, 0.012223754, 0.01500793, 0.033787254, 0.03693748, 0.062427666, -0.060164828, 0.03651597, 0.04516799, 0.042683307, 0.00044681315, -0.020354437, 0.00082707225, -0.029505612, -0.010177218, -0.037292432, -0.02935032, -0.017958492, 0.0016999005, 0.035318, 0.0044008843, -0.025445817, -0.008890507, 0.009395208, 0.021297283, -0.0025956065, -0.024669355, 0.018679494, 0.047741413, 0.04574479, 0.0031613156, -0.008973699, -0.023449197, 0.024913386, -0.017448245, -0.04459119, 0.031746265, 0.033521038, -0.026776899, 0.042283982, -0.0003781793, 0.0039155944, -0.0019813685, -0.058168206, -0.038712252, 0.005596083, 0.006400278, -0.014031804, 0.006039777, 0.0009379956, 0.0076537114, 0.032988608, 0.03305516, -0.04982677, -0.05452992, 0.00047385073, 0.036316305, 0.031280387, -0.018934617, -0.009883271, 0.00049048924, 0.018335631, -0.00095602067, 0.0309698, 0.07267699, -0.03334356, -0.022628365, 0.009650332, -0.04933871, 0.04026518, -0.011275359, -0.02435877, -0.03380944, -0.025401449, -0.022550719, 0.00648347, 0.03001586, -0.0102160415, -0.04609975, 0.006566663, -0.01785866, -0.008008666, 0.036582522, 0.027198408, -0.0098444475, 0.03713714, 0.04911686, -0.0185242, 0.0067219553, 0.028196717, -0.014542052, 0.006477924, -0.024669355, 0.03489649, 0.06841753, -0.039732747, -0.006350362, -0.07227766, 0.030193338, -0.017182028, 0.039022837, -0.009195547, -0.011624767, 0.013887604, 0.0024930025, 0.035961352, -0.038002342, -0.022872396, -0.016117163, -0.013721219, -0.025246156, 0.0041845837, 0.053021364, -0.053110104, -0.031945925, 0.01104242, 0.019788727, 0.050802898, 0.021452578, 0.011513844, -0.00422618, -0.024735909, 0.010593181, -0.018069414, -0.044391528, 0.025379265, -0.022872396, 0.060919106, -0.01800286, -0.020875776, 0.010981413, 0.031590972, -0.053731274, -0.003996014, -0.018102692, 0.061762124, -0.0092621, -0.03600572, 0.04392565, 0.03376507, -0.031369124, -0.007881104, -0.039533082, 0.022251226, 0.008701937, -0.02631102, 0.032323066, 0.0076148883, 0.05262204, -0.02864041, 0.027841762, -0.027287146, -0.039821483, -0.06406933, -0.055506047, -0.004694831, 0.03576169, 0.016849257, -0.016727243, 0.0040459293, -0.024758093, -0.0058345688, -0.028773518, 0.022217948, 0.012745094, 0.030215522, -0.067219555, -0.023449197, -0.0019023356, 0.032411806, 0.024048183, 0.04334885, -0.020665022, 0.011219897, -0.0119908145, -0.045700423, -0.033942547, -0.05674839, -0.050270464, -0.021119807, -0.004595, -0.009605963, -0.042150874, -0.019067725, -0.0045062616, 0.04667655, 0.029461244, -0.020831406, 0.0072543877, 0.035539843, 0.036582522, 0.01667178, -0.036405046, -0.036538154, -0.03396473, -0.024159107, -0.026865637, -0.018313447, 0.042350538, -0.018324539, -0.0059399456, 0.04574479, 0.026621606, -0.06819568, 0.031080725, -0.016549764, 0.015518177, 0.017814292]

```

**Please describe your setup**

- [ ] MemGPT version
`memgpt version`
0.2.10
(pymemgpt_nightly-0.2.10.dev20240101103910)

- [ ] How did you install memgpt?
 `pip install pymemgpt-nightly`
- [ ] Describe your setup
OS: Linux
Running from terminal

```
[model]
model = ehartford/dolphin-2.5-mixtral-8x7b
model_endpoint = https://api.memgpt.ai
model_endpoint_type = vllm
model_wrapper = chatml
context_window = 32768

[embedding]
embedding_endpoint_type = hugging-face
embedding_endpoint = https://embeddings.memgpt.ai
embedding_model = BAAI/bge-large-en-v1.5
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = local
```

**Comment by cpacker** [comment]
> embedding_dim = 1536

in your config needs to be

> embedding_dim = 1024

See: https://github.com/cpacker/MemGPT/blob/main/configs/memgpt_hosted.json#L10

To fix you can do `memgpt quickstart --latest`
