### ISSUE TITLE
Proxy seems not working

### ISSUE THREAD

**Issue by SingL3** [cpacker/MemGPT#98]
I have build a proxy for openai on cloudfare and I got the below error:
(I have export OPENAI_API_KEY and OPENAI_API_BASE)
```
Traceback (most recent call last):
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/mnt/data/conda/envs/oasst/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/mnt/data/conda/envs/oasst/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/mnt/data/conda/envs/oasst/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/mnt/data/conda/envs/oasst/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/mnt/data/conda/envs/oasst/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/openai/api_requestor.py", line 668, in arequest_raw
    result = await session.request(**request_kwargs)
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host cf.workers.dev:443 ssl:default [Network is unreachable]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/home/xxxxxx/openai_service/MemGPT/main.py", line 331, in <module>
    app.run(run)
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/mnt/home/xxxxxx/openai_service/MemGPT/main.py", line 329, in run
    loop.run_until_complete(main())
  File "/mnt/data/conda/envs/oasst/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/mnt/home/xxxxxx/openai_service/MemGPT/main.py", line 142, in main
    faiss_save_dir = await utils.prepare_archival_index_from_files_compute_embeddings(FLAGS.archival_storage_files_compute_embeddings)
  File "/mnt/home/xxxxxx/openai_service/MemGPT/memgpt/utils.py", line 235, in prepare_archival_index_from_files_compute_embeddings
    embedding_data = await process_concurrently(archival_database, embeddings_model)
  File "/mnt/home/xxxxxx/openai_service/MemGPT/memgpt/utils.py", line 218, in process_concurrently
    i, result = await future
  File "/mnt/data/conda/envs/oasst/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/mnt/home/xxxxxx/openai_service/MemGPT/memgpt/utils.py", line 211, in bounded_process_chunk
    return await process_chunk(i, chunk, model)
  File "/mnt/home/xxxxxx/openai_service/MemGPT/memgpt/utils.py", line 203, in process_chunk
    raise e
  File "/mnt/home/xxxxxx/openai_service/MemGPT/memgpt/utils.py", line 200, in process_chunk
    return i, await async_get_embedding_with_backoff(chunk['content'], model=model)
  File "/mnt/home/xxxxxx/openai_service/MemGPT/memgpt/openai_tools.py", line 124, in async_get_embedding_with_backoff
    response = await acreate_embedding_with_backoff(input = [text], model=model)
  File "/mnt/home/xxxxxx/openai_service/MemGPT/memgpt/openai_tools.py", line 98, in wrapper
    raise e
  File "/mnt/home/xxxxxx/openai_service/MemGPT/memgpt/openai_tools.py", line 76, in wrapper
    return await func(*args, **kwargs)
  File "/mnt/home/xxxxxx/openai_service/MemGPT/memgpt/openai_tools.py", line 117, in acreate_embedding_with_backoff
    return await openai.Embedding.acreate(**kwargs)
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 73, in acreate
    response = await super().acreate(*args, **kwargs)
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/openai/api_requestor.py", line 372, in arequest
    result = await self.arequest_raw(
  File "/mnt/data/conda/envs/oasst/lib/python3.10/site-packages/openai/api_requestor.py", line 685, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
```
But if I use `curl`, I can reach successfully:
```
  curl $OPENAI_API_BASE/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'
```
Response:
```
{
  "id": "chatcmpl-8CkRwnghIqaKT2E7RWz9UnH9UsfQF",
  "object": "chat.completion",
  "created": 1698049180,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Hello! How can I assist you today?"
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 19,
    "completion_tokens": 9,
    "total_tokens": 28
  }
}
```

Any suggestions?

**Comment by SingL3** [comment]
@cpacker 
Thank you for you fast reply!
I have follow another issue by setting `openai.proxy` in `openai_tools.py` and it works.([here](https://github.com/cpacker/MemGPT/issues/24#issuecomment-1767987562))

**Comment by SingL3** [comment]
@cpacker 
I keep receiving rate limit error:
```
💭 Bootup sequence complete. Persona activated. Testing messaging functionality.

💭 User has logged in. Last login: never. Got it. Ready to greet and assist in document analysis tasks.
🤖 Hello Chad, welcome! How can I assist you with your documents today?
Enter your message: AOSS 的 SDK具体是啥？给出具体示例
💭 The user has asked about the SDK specifics of AOSS. I need to cross-reference this in my archival memory and provide a detailed answer.
⚡🧠 [function] updating memory with archival_memory_search:
        query: AOSS SDK, page: 0
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
acreate (backoff): caught error: Rate limit reached for gpt-4 in organization org-uL6ErIyeknQXybIzTsylefqn on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us
through our help center at help.openai.com if you continue to have issues.
⠹ Thinking...
```
Any suggestions?

**Comment by cpacker** [comment]
This error is pretty specific - you're being rate limited, see OpenAI's page for more details [here](https://platform.openai.com/docs/guides/rate-limits).

If you're not trying to use OpenAI but you're still getting this error, something must be going wrong because the code is calling for gpt-4 at an OpenAI endpoint (and getting rate limited).
