### ISSUE TITLE
Azure OpenAI: KeyError: 'function_call'

### ISSUE THREAD

**Issue by ArneJanning** [cpacker/MemGPT#980]
**Describe the bug**

At the first call to the LLM using Azure OpenAI/GPT-4 right after starting MemGPT I get this error:

```
An exception occurred when running agent.step(): 
Traceback (most recent call last):
  File "box/box.py", line 592, in box.box.Box.__getitem__
KeyError: 'function_call'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 631, in box.box.Box.__getattr__
  File "box/box.py", line 619, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'function_call'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 633, in box.box.Box.__getattr__
AttributeError: 'Box' object has no attribute 'function_call'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arne/src/MemGPT/memgpt/main.py", line 347, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arne/src/MemGPT/memgpt/main.py", line 323, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
                                                                                          ^^^^^^^^^^^^^^^^^^
  File "/home/arne/src/MemGPT/memgpt/agent.py", line 673, in step
    raise e
  File "/home/arne/src/MemGPT/memgpt/agent.py", line 597, in step
    if verify_first_message_correctness(response, require_monologue=self.first_message_verify_mono):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arne/src/MemGPT/memgpt/utils.py", line 671, in verify_first_message_correctness
    if require_send_message and not (response_message.function_call or response_message.tool_calls):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 647, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'Box' object has no attribute 'function_call'"

```
**Please describe your setup**
- [ ] How did you install memgpt?
  - `git clone`, `poetry install`
- [ ] Describe your setup
  - What's your OS: Linux/WSL2
  - How are you running `memgpt`? Terminal/ZSH
---

**Comment by ArneJanning** [comment]
He @cpacker , thank you for the quick fix!

I checked out #982 and re-ran `memgpt configure`.

Ran into an error right after the start before the first call to the LLM:

```
  File "/home/arne/src/MemGPT/memgpt/llm_api_tools.py", line 255, in azure_openai_chat_completions_request
    assert resource_name is not None, "Missing required field when calling Azure OpenAI"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
```

Turns out that the `embedding_deployment` and `endpoint` values were missing from the `[azure]`-section in the `credentials`-file. After adding them manually, everything worked as expected. 

And yes, we have to run `--no-verify` with `memgpt run` otherwise memgpt get's stuck in "thinking...".
